### ISSUE TITLE
cf push with environment variables

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/cli#1012]
* Command  
cf push

* What occurred, incl. error and/or stack trace
At the moment the only way to pass environment variables is via the manifest.yml or via cf set-env & cf restage. The manifest doesn't seem to be a good place for storing secure tokens. In this way we need to set tokens and passwords via set-env. This requires a cf restage after a fresh push and doubles the deployment time in this way.

* What you expected to occur
Please introduce a way to set environment variables on cf push.

* CLI Version  
cf version 6.21.1+6fd3c9f-2016-08-10

* CC API Endpoint Version  
API version: 2.58.0

**Comment by elgohr** [comment]
Ping

**Comment by dkoper** [comment]
Hi @elgohr 

Thanks for pinging.
I agree that the manifest is not a good place for storing secure information. It is not considered good practice to mix secure information with information that is not so sensitive (like most information in the manifest). As soon as you add one secure piece of information in the file, the whole file needs to be managed more securely, and that can easily be overlooked.

The best practice for now (until hopefully CredHub or some initiative opens up new possibilities) is to inject them using a user-provided service.
https://docs.cloudfoundry.org/devguide/services/user-provided.html
http://cli.cloudfoundry.org/en-US/cf/create-user-provided-service.html

You create the user provided service once, then use the manifest file to have it bound to your app.
When you update the credentials, you only need to restart the app (no re-stage).

Regards,
Dies Koper
CF CLI PM

**Comment by sbaxter** [comment]
+1 on this one.

In addition to security concerns, it would be much easier for automation scripts to handle defining environment variables. My current paradigm is to `cf push` with the `--no-start` flag; then `cf set-env`; and `cf start`.

**Comment by dkoper** [comment]
@sbaxter I was suggesting something like `printf $MYPWD | cf cups service-pwd -p "password"`, after which you can simply add `service-pwd` as a service in your app manifest. Why do you prefer using `cf set-env`?

**Comment by sbaxter** [comment]
User-provided services doesn't work for my use-case; I deploy a lot of apps that are CF agnostic: parsing `VCAP_SERVICES` isn't an option from within these apps.

I do not _prefer_ to use `cf set-env`; my preferred method would be something like `cf push -e 'MVAR=MYVALUE'`. Right now we either push followed by `set-env` or we `sed/awk` the manifest.yml.

**Comment by pourquoi42** [comment]
+1 ... it's nearly impossible to use docker otherwise. E.g.:
```
>cf push --no-start --docker-image influxdb myinfluxdb

FAILED
Error reading manifest file:
env var 'influxdb_metric_password' should not be null
env var 'influxdb_metric_username' should not be null

```

**Comment by navionguy** [comment]
My choice would be able to use the following manifest syntax,

 env:
     SECRET: $(uuidgen)

That way, secret is generated at the push, but only exists within the final app image.  That way, as the app scales out, all instances share the same secret.

**Comment by nathan-alden-inl** [comment]
I need the ability to set the `ASPNETCORE_ENVIRONMENT` environment variable during a `cf push`. I don't want to create copies of my `manifest.yml` just to change `ASPNETCORE_ENVIRONMENT` from space to space. As it stands, I am either forced to copy manifests or use the workaround posted by @sbaxter.

**Comment by ttecho** [comment]
+1 we would leverage a cf push -e ```NAME_OF_ENVIRONMENT_VARIABLE=xyz```

**Comment by harneet1** [comment]
how to deploy microgateway in cloud foundry link is https://github.com/CAAPIM/Microgateway

**Comment by harneet1** [comment]
How to set environment variable of docker app. Which has been stated in docker compose file. Is it possible to push docker image then after that using set-env to initialize environment variable and how to pass certificate which has stated in docker compose to docker app deployed in cloud foundry. I am using PCF DEV.

**Comment by elgohr** [comment]
V3 already seems to provide a way to set it on push (http://v3-apidocs.cloudfoundry.org/version/3.39.0/index.html#create-an-app). Would be awesome if the CLI could support it.

**Comment by XenoPhex** [comment]
Hi @elgohr thanks for creating this story. We have a variable substitution [epic](https://www.pivotaltracker.com/epic/show/3904246) which we believe will solve the issue you've raised. The feature allows you to leverage vars.yml files (used in conjunction with the -f manifest feature) to store credentials. Please do not hesitate to let us know if you have any feedback. After we release, if it is still not sufficient, please open a new issue. Thanks.

**Comment by shakuzen** [comment]
@XenoPhex according to [this comment in the Value Substitution in App Manifest Proposal](https://docs.google.com/document/d/1yax7Hjw_YJiKwh2aAwY3r-BtuDpJvoUaPvQ7B3sTju4/edit?disco=AAAABlrPmQs):

> we will only support substituting a single value in a manifest with a single value in a substitution file

So this would only solve the case that every desired environment variable is known beforehand and written in the manifest file with its value as a variable placeholder. It does not solve the case where you want to pass arbitrary environment variables or conditionally pass environment variables when pushing an application, I believe.

**Comment by elgohr** [comment]
@XenoPhex I'm totally with @shakuzen. If I wanted a substitution file, I would use https://github.com/cloudfoundry-incubator/spiff/blob/master/README.md

**Comment by XenoPhex** [comment]
If I'm understanding the topics brought up in this issue, there are two core problems:
1. Devs need a way of securely adding env vars (which contain credentials/secrets/etc.) to their apps.
1. Devs need a way of dynamically adding/updating env vars at push time.

In discussing the first issue Dies brought up some solutions:
1) Using user provided services - which does not work for docker apps/apps that require specific environment variables to be set. (Which I'm assuming is due to internal dependencies that the app developer does not have control over.) This has historically been the recommended way of storing and sharing secrets for an application. We recognize this doesn't work for everyone, but try to sway people towards this direction whenever possible.
2) Using environment variables - which either requires hacking something together to fill these values in an insecure plain text file (aka the `manifest.yml`) or additionally calling `cf set-env`+other commands. We believe that the [variable substitution](https://www.pivotaltracker.com/epic/show/3904246) should take care of having to write these secrets to disk and follows the patterns set forward by the [fly](https://concourse-ci.org/setting-pipelines.html#section_pipeline-params) and [bosh](https://bosh.io/docs/cli-int/) CLIs. In order to make things a bit easier to set values dynamically, I've added the [following story](https://www.pivotaltracker.com/story/show/156854286).

Ideally, as Dies suggested above, these credentials would be set via CredHub and the platform would link them to your app so the CF CLI would not have to be aware of any credentails. But that integration/work outside the scope of this team.

As for the second issue from the top:
1) The v6 version of the CF CLI has never provided a way to dynamically _add new_ environment variables to an app during `push` via command line.
1) The v6 version of the CF CLI has never provided a way to dynamically _update existing_ environment variables to an app during `push` via command line.

Trying to keep this answer as brief as possible - we have no plans on adding support for this feature. The push command currently has 22+ flags (on the current edge build) and over a dozen manifest properties it has to combine/resolve in order create/update a given app and it's getting too difficult to maintain this complexity - especially across multiple CC API versions. Additionally, we are moving [almost] all the logic around the `manifest.yml` into the Cloud Controller. So trying to resolve flags + manifest is going to get funky going forward and we're still trying to figure out how to proceed. We'll keep this feature in mind as we expand into the new world of apps and processes via the v3 API and will try to have someone reach out directly to get more feedback in the future.

### Notes:
- If you're unsure how to avoid writing the vars-file to disk, follow this example we use with `fly` and the output of the lastpass CLI: https://github.com/cloudfoundry/cli/blob/master/ci/bin/reconfigure-pipelines#L32-L37
- @elgohr Spiff has effectively been deprecated, while it continues to work, I'd recommend [spruce](https://github.com/geofffranks/spruce) if you want a more powerful substitution tool that's actively being maintained.

**Comment by elgohr** [comment]
How would you push the user provided service itself? This is just having the same problem to the next app, which has to be pushed.

So we stick with the hacking solution? 

I mean Credhub would totally solve this. If you have a look at the date, when this issue was raised, you'll realize that it was before Credhub was announced. At CF Summit in Basel they talked about big plans, but need time. I wouldn't like to wait another year.

**Comment by XenoPhex** [comment]
I'll check in with the relevant backend teams to see what the status of the integration is (after CF Summit) and we'll figure out how to proceed. But to be honest, there are so many other features on our team's docket that are much higher priority, the soonest we could even _think_ about this feature would be in 6 ~ 8 months (assuming nothing gets added to our priority list).

Considering how long this feature has been open, we honestly didn't want to give you false hope of us being able to add it.

**Comment by elgohr** [comment]
Ping

**Comment by sarathkr** [comment]
ping

**Comment by swidnikk** [comment]
ping

**Comment by XenoPhex** [comment]
I remember checking a few weeks after summit, and the response I got was "it's still under development and it could take a while". Not sure what the status is now.

/cc @abbyachau

**Comment by skypeter1** [comment]
It would surely be something of great help for automation

**Comment by slw07g** [comment]
ping

**Comment by XenoPhex** [comment]
So in the new CCV3 API/CF CLI V7 world, a lot of CF push logic has been moved from the CF CLI into the Cloud Controller. I would recommend reaching out to the CC or VAT team around this issue as it's more under their domains now. It's unlikely this will change in the CF CLI V6 world. Sorry 😞.

**Comment by elgohr** [comment]
@XenoPhex so where would I find CC or VAT?

**Comment by XenoPhex** [comment]
@Gerg @heyjcollins can you help facilitate this?

**Comment by heyjcollins** [comment]
I'm the CLI PM
@Gerg is the VAT pm.

**Comment by Gerg** [comment]
I'm trying to catch up on this thread. 

Now that [app manifest variable substitution](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#variable-substitution) is available, what are the remaining gaps? 

For example, I was able to do the following:

manifest.yml:
```yml
---
applications:
- name: some-app
  env:
    SECRET: ((secret))
```

```sh
cf push --manifest manifest.yml --var secret=my-secret
...
```

```sh
cf env some-app
...

User-Provided:
SECRET: my-secret

...
```

**Comment by elgohr** [comment]
@greg thank you for the hint. Nothing. Since when is this available?

**Comment by Gerg** [comment]
Looks like it is available starting with CLI version v6.37.0 and API version 2.69.0.

Source: https://lists.cloudfoundry.org/g/cf-dev/message/8026

**Comment by vinaypotluri** [comment]
Can i pass the git commit ID or branch name to one of the env vars in manifest.yml without having to manually fetch it ?

Something like COMMIT_ID: `git rev-parse --short HEAD`

**Comment by mohanbabubb** [comment]
> 
> 
> +1 we would leverage a `cf push -e NAME_OF_ENVIRONMENT_VARIABLE=xyz`

no more exists
