### ISSUE TITLE
Check Route does not allow for port

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cli#1023]
* Command  
`cf check-route`

* What occurred, incl. error and/or stack trace
No mention of `--port` in the help text

* What you expected to occur
`--port` being a supported option

* CLI Version  
6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  
https://api.local.pcfdev.io (API version: 2.58.0)

* Platform & Shell Details  
Mac OS X 10.11 stock Terminal

* Any other relevant information  
I don't know if this is a bug, but it seems odd to me that I can create, delete, map and unmap a route by port, but can't check if it exists.

**Comment by dkoper** [comment]
Hi @twoseat 

Apologies for the late reply - I thought I had responded.

When we exposed TCP routes (a year ago now), I noticed `check-route` took the hostname as a (mandatory) argument, meaning you can't check for routes without hostnames either, and no-one has ever raised that as being an issue.
Hence I felt this is a rarely used command, so considered adding support for routes with paths and TCP routes low priority. Indeed, a year has passed since someone, you, brought it up!

Other than it seeming odd (which it is), are you in great need for this feature?

Cheers,
Dies Koper
CF CLI PM

**Comment by twoseat** [comment]
Hi @dkoper - I found the issue during testing for the part of the CF Java Client that mirrors the CLI. As I'm not a 'real' user of the CLI I have no particular need for the fix (which we now have in the client), so I'm happy for you to decide the priority and close this issue as you see fit. Thanks!

**Comment by dkoper** [comment]
Thanks. I'll leave it open for a while in case anyone wants to jump in, else I may close it as a todo that we'll not likely get to any time soon.
(And refer people who need it to the Java Client ;))

**Comment by dkoper** [comment]
Closing - this doesn't seem to be a feature anyone is eagerly waiting for.
