### ISSUE TITLE
Add the ability for CF to unzip an artifact that could contain 1 or more files

### ISSUE THREAD

**Issue by pivotal-manuel-morales** [cloudfoundry/cli#1028]
Currently to push an application that does not get packaged/zipped (.NET, NodeJS, Golang) I just go to the root directory of the project where the manifest.yml file is and run "cf push" without specifying a file to upload. If the file is a .jar or .war file I can specify to upload just that file. It would be nice if I could specify a packaged file (.zip, .tar) that contained my .NET, NodeJS or Golang app.

Here is an example: The CI/CD tool can create artifacts that are directories or single files and these artifacts can be passed around to different parts of the deployment project. The add-ons we wish to use require a single file to be specified for uploading, which works fine for Java apps but not apps written in .NET, NodeJS, Golang, etc. I can tell Bamboo to package up a directory into a single file and keep it as an artifact but Cloud Foundry will not accept that packaged/zipped file when doing the push. Because of this, the deployment projects differ from language to language. If CF can take packaged/zipped files then our deployment process will be the same for every app, regardless of what language is being used.

It would also be nice to be able to store artifacts as a single, packaged file and not have to un-package them every time I want to do a push.

A solution might be to have CF have a step to unpack/unzip a file BEFORE running the any of these detect.sh scripts for each build. That way the first thing it does after a file is uploaded would be to check if it needs to be unpackaged/unzipped and if so then do it then carry on like normal.

**Comment by dkoper** [comment]
Hi @pivotal-manuel-morales 

The CLI would not know whether your zipped file is intended to be deployed as a zip file (because e.g. you are using CF as a web server (static buildpack) to host a zip file, or is actually an archive with your app.
I'm not keen on introducing some flag to `push` to tell it that it's a compressed file that should be unpacked before pushing: then you would still have a different deployment process for this type of app. Also, the flag would basically be an alias for `unzip myapp.zip | cf push myapp` - I think our development resouces could be spent more wisely.

Note that the CLI unzips archives (and rezips them again) regardless, to send a list of the files within with their checksums to CC's resource matching API to see if there are any (big) files in CC's cache that we don't need to resend. So there is no performance gain to specifying an app archive as opposed to an "exploded" app.

I don't know the details of how a pushed app is presented to the buildpacks, but your suggested solution sounds better as it would be up to the buildpack (which can better determine whether unpacking an archive makes sense for the language) - as the Java buildpack does:
As you say, their detect.sh script could decide to peek inside the archive to see if they could run it if unpacked, and unpack if need be.

Why not send a feature request to the buildpacks team?

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
@pivotal-manuel-morales Did you send a request to the buildpacks team? Care to post a link to the issue here?

**Comment by dkoper** [comment]
Closing, I don't think there is anything we can do.
