### ISSUE TITLE
enhancement request: show app logs during standard cf push during app start

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#1031]
* Command  
e.g. `cf push myapp`

from a user (i think @tomwhoiscontrary) with experience working with cloud foundry and the cli:

```
Hi,

This is a bit of an idle thought.

'cf push' prints out the logs relating to the staging of the app. Would it be possible for it to continue to print logs after staging, as the app starts, until it finishes starting up? Not by default, but when given a --logs flag or something. I have no idea how cf push gets the staging logs, so i don't know if this is low hanging fruit, or would require a complete re-architecting. This would allow someone pushing an app to get faster feedback on how the start-up is going.

My motivation here is that we have a moderately complicated deployment process which sometimes fails, and rolls itself back when it does. When it rolls back, it deletes the apps it's just pushed, and in doing so wipes out the recent logs that CF stores. That makes it tricky to diagnose failed deployments. Being able to cf push --logs would let us collect all the crucial logging in the output of our deployment script.

Regards,
tom
```

we should consider whether we can think of a downside for showing the app logs by default as "cf push" without any additional arguments? one downside is that we currently show the app status as a cadenced log message. if we show the app logs, then we'd have to consider how to adjust the cli UX for that.

**Comment by dkoper** [comment]
This sounds similar to #910, although you are suggesting to print them depending on setting a flag instead of on app start failure.
A concern I had with #910 that I haven't been able to validate yet is the risk of unintentionally & unexpectedly printing credentials or other sensitive information on cf push from those logs when users don't expect it - a flag could address that.
That said, with the upcoming `run-task` command we considered printing the task's logs to stdout but the feedback I got was that users prefer to run `cf logs` (or use existing tools like papertrail) to analyse the logs - we'll first release `run-task` without printing logs and reconsider when we get more user feedback.

What is the purpose of showing the logs at push in your view? How long would we show these logs for? Would `cf push` "hang" and tail the logs "for ever", or only for the time we're polling the app state until one of its instances has started?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
For the person you received that feedback from, why don't they just run `cf push their app || cf logs theirapp --recent` so they have the logs before they delete it?

**Comment by jbayer** [comment]
i've asked tom to reply here

**Comment by tomwhoiscontrary** [comment]
Original idle thinker here ...

> What is the purpose of showing the logs at push in your view?

To make it simple to collect logging of application startup in our deployment script, so that we can diagnose failed pushes more easily.

> How long would we show these logs for? Would cf push "hang" and tail the logs "for ever", or only for the time we're polling the app state until one of its instances has started?

I'd like it to show logs from each instance until it has started successfully.

> why don't they just run cf push their app || cf logs theirapp --recent so they have the logs before they delete it?

That would be better than what we have now, that's for sure! However, we're using Spring Boot, which produces enormous amounts of logging, so `logs --recent` at the end of startup doesn't cover everything. We could do something like `cf push & cf logs theirapp`, but getting that right is mildly tricky - we have to retry `cf logs` until the app is created, then detect app startup and kill it, and even then we risk missing a bit of logging at the start. We could do it, but the CF CLI could do a better job of it.

**Comment by dkoper** [comment]
Hi @tomwhoiscontrary 

Thanks for joining!

It seems everyone has a use case that requires a new flag on `cf push` because the CLI could do it better, so we'd like to take our time validating it benefits enough people.

For the issue that your runtime produces too much logging and `cf logs --recent` could miss out, you could push with `--no-start` first to ensure the app exists, then run `cf logs yourapp &` before you `cf start yourapp ; kill <cf logs's process>`: no need to retry, no need to detect app startup, no missing a bit of logging, only need to look up how to reliably find the right pid on your platform (`ps`, `lsof` on the log file if you direct it to disk, etc.).

Please let us know how that goes - if it turns out that the behaviour doesn't satisfy completely, a --logs option wouldn't either..
