### ISSUE TITLE
cli 6.23.0 doesn't build with e.g. go-1.6.2 anymore

### ISSUE THREAD

**Issue by svollath** [cloudfoundry/cli#1035]
Building cli-6.23.0 using go-1.6.2 failed.
The changelog for cli-6.23.0 lists "built with go-1.7.4", and as reason you're linking to a page which recommends to use version go-1.6.1 or above.
As long as there's no other reason to not support go-1.6.1 anymore, it would be great if one could use it.

* Command
Build cf-cli using e.g. go-1.6.2

* What you expected to occur
cf-cli to build with go-1.6.1 or above (1.6.X)

* Platform & Shell Details  
openSUSE Leap 42.2

**Comment by dkoper** [comment]
Hi @svollath 

The switch from golang 1.6 to 1.7.1 resolved #763.

Having not confronted with such a request before, we simply use the latest version if its changelog reports any advantages and after that don't spend any additional time confirming whether our code builds on older versions.
We'd have to weigh the effort it would take to investigate why its failing on previous versions (you didn't include any details) and the impact to our code to address it, against the merits of doing so (you didn't include any). We would not want to see the issue of #763 reappear again.

Regards,
Dies Koper
CF CLI PM

**Comment by XenoPhex** [comment]
I figured I'd add some additional information incase other people stumble upon this issue.

When the development team works on the CLI, we all use the latest recommended version of GoLang as to keep up with the [GoLang] community. This usually means that unless there's a major issue, we're on the latest stable within 2 business days of a release. At the same time, our testing/release pipelines also get upgraded, so we cannot guarantee that the CLI will be functionally equivalent (or even compile) on previous versions.

That being said, there are several technical reason why we require a minimum of 1.7.*:
1. For Linux and Windows, the CLI pipeline [statically compiles](https://github.com/cloudfoundry/cli/blob/d7757df14d2fbe3e14c4e81d3ff2f63050898582/ci/cli/tasks/build-binaries.yml#L29:L38) the binary as per issue #807. The issue was that the built in DNS resolution mechanism wasn't working properly (the previously mentioned #763) until [1.7.1](https://github.com/golang/go/issues/16865).
1. For MacOS (AKA Sierra and above), GoLang 1.6 just flat out doesn't work (see #944).
1. There have been some [changes](https://golang.org/doc/go1.7#encoding_json) in the built in `json` library that affect the communication between the CLI and the Cloud Controller as well as the way we display some JSON output. Since we only test on 1.7, we don't know how strongly this affects us.

Just as a warning, we've already have several issues (#951 and [Tracker Story #134888875](https://www.pivotaltracker.com/story/show/134888875)) that will be fixed when 1.8 comes out in a few months. So I'd recommend trying to upgrade to the latest GoLang when possible.

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue, or ask us on slack or the CF Dev mailing list if you have more questions.
