### ISSUE TITLE
Github Releases & Binaries

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/cli#1044]
Please attach the binaries to the Github release.

Currently, a release's description includes links off to binaries which are not actually part of the release. This makes it difficult to programmatically access the released binaries, such as with Concourse's https://github.com/concourse/github-release-resource.

**Comment by dkoper** [comment]
Hi @cholick 

We don't want to host our binaries on GitHub as it does not offer us the download stats we have now.
I'll ask my team if they have any alternative suggestions.

Regards,
Dies Koper
CF CLI PM

**Comment by XenoPhex** [comment]
Sorry for the delayed reply!

We've discussed using Github releases in the past and there are two main reasons why we don't:
- We track basic download statistics for each platform/architecture. We can't do this (to the same granularity) with Github release links.
- The release links that are provided by Github require us to upload these packages/binaries directly to Github without additional information. This means that the Github API links doesn't have a concept of platform/architecture, so you're not sure which one you might be downloading. (I don't believe the filename is contained in the link, but this could have changed.) Since we support multiple platforms, you'd be playing roulette with what you'd be downloading.

There was a thought to upload just the linux64 binary to each release for said concourse resource, but there's no way to hide the auto generated link, and we'd potentially lose tracking information.
