### ISSUE TITLE
No Way to Examine Process Types of an Application Without First Starting It

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cli#1046]
Currently the only way to examine the command tied to a process type for an application is to start (or restart) it successfully.  In addition, this can only be done for the `web` process type.  This makes diagnosing command line problems difficult (you cannot visually scan for a problem) and prevents you from seeing options other than the `web` process type.

With the addition of tasks, we now need a way to see the command lines created during staging, so that they can be re-used or appended to for task execution.  Note that this has already been experienced by someone on [Stack Overflow](http://stackoverflow.com/questions/41313079/accessing-the-java-executable-from-a-cloudfoundry-task-command-cf-run-task).

A non-binding suggestion would be that `cf app` include the contents command lines from all process types declared during staging.

**Comment by dkoper** [comment]
With the V3 commands, you can push an app with staging it, then run `v3-stage`  and `v3-set-droplet` to stage it and then `v3-app` will show the app's process types.
We've been reluctant to include the process' `command:` as we understand that they can be very long (multiple lines) cluttering the output in the common case where one is not interested in the command.

**Comment by dieucao** [comment]
I'd agree that having a way to output/see the commands for the processes without having to parse the raw curl output seems useful/important.

**Comment by abbyachau** [comment]
cc @zrob for visibility

**Comment by abbyachau** [comment]
Hi @nebhale thanks for reaching out - in [`v6.38.0`](https://github.com/cloudfoundry/cli/releases/tag/v6.38.0) we updated `cf app` to display app instances by process type. Please let us know if you have any feedback on this change. 

In this [issue](https://www.pivotaltracker.com/story/show/160001779) we are tracking the feature request to add the start command back to `cf app`. I believe this was removed due to feedback from customers that displaying that information is a security concern. Please follow this issue for updates - it's likely we'll add the ability to view the start command in the V7 CLI but have yet to prioritise the work. 

Please let us know if there's anything else to be done here, or if you are happy for us to close this issue. Thanks again.
