### ISSUE TITLE
symlinks in push folder

### ISSUE THREAD

**Issue by lukaslehmann** [cloudfoundry/cli#108]
Hi guys,

If I have a symlink in my application then this symlink will just be ignored.
Is it planned to grap the files from the target directory and include it in the generated zip file? :)

Bests,
Lukas

**Comment by gerhard** [comment]
I just came across this today. My symlink was `id_rsa.pub -> archer_20150104_rsa.pub`. There are legit cases for symbolic links such as indirection (my case), backwards-compatibility etc.

A hard link did the trick for me, but this is definitely going on my `cf` snag list.

**Comment by olavmrk** [comment]
I also ran across this problem today. My use case is that I need a symlink from a directory in my web root to a specific directory in a vendor package. I cannot simply copy the directory into the web root, because that would mess up relative references in files in that directory. Instead, I was planning to use a symlink, like so:

```
ln --symbolic --force --no-target-directory --verbose "../$SSP_DIR/www" 'www/simplesaml'
```

Note that the symlink is relative, so its location in the file system does not matter.

**Comment by giner** [comment]
Same problem here. It should not remove **relative** symlinks.
