### ISSUE TITLE
Error cf push

### ISSUE THREAD

**Issue by hendisantika** [cloudfoundry/cli#1132]
Hi, I try to run this [repo](https://github.com/cloudfoundry-samples/hello-spring-cloud/blob/master/manifest.yml) 
I have created manifest.yml. 
Then I want to push with 
`cf push`
But it's said that : 
```
FAILED
Error reading manifest file:
yaml: line 14: did not find expected key
```

Then I binded a service with 
`cf bind-service hello-spring-cloud postgres-service`
then
```
FAILED
App hello-spring-cloud not found
```
FAILED again, I already follow the manifest.yml application name.

Why does It happen?
How to solve this issue?

Thanks

**Comment by dkoper** [comment]
Hi @hendisantika 

Can you post your cf CLI version (use `cf -v`) and app manifest file?

The manifest file in the repo you linked to was updated two days ago.
In the latest version, there is no line 14. Guessing you used an older one?
I was able to push an app with the version before that (see https://raw.githubusercontent.com/cloudfoundry-samples/hello-spring-cloud/5192344b5c7aa05a7e40a3fb06cf620281f898df/manifest.yml).
Line 14 in this version has `  env:`.
The error you reported seems to indicate that the cf CLI did not recognize the `env` key.
Maybe the cf CLI version is too old (although I believe this key has been supported for over two years), there is a space or other character before or after the key that confused the CLI, etc.
Because the CLI failed to parse the manifest file, the application was not pushed, causing the app not found error on `cf bind-service`.

Regards,
Dies Koper
CF CLI PM
