### ISSUE TITLE
CLI should report apps staged using outdated buildpacks

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#1193]
## Command  

Any of the following commands:

cf apps
cf app myapp
cf start myapp
cf stop myapp
cf restage myapp

## What occurred

If an application is staged using an outdated buildpack none of the commands above report it

## What you expected to occur

cf apps: visually highlight apps using an outdated buildpack
other commands: emit a warning, suggesting to upgrade to the latest version

## CLI Version  

6.29.0

## CC API Endpoint Version  

2.74.0

## Any other relevant information  

- this should also be the case also when using system buildpacks, not just for remote buildpacks

**Comment by dkoper** [comment]
With the current APIs I suppose the CLI could detect whether the buildpack used to stage an app still exists (buildpack guid still in list of available buildpacks).

@sclevine @nebhale
I believe you release new versions of the system buidpacks every month if not more often. Are users expected to repush their apps so often?

**Comment by CAFxX** [comment]
Ideally only for security issues @dkoper.

I suppose this feature will require changes beyond the CLI though. And I would recommend to consider also non-system buildpacks.

**Comment by nebhale** [comment]
I’ll just speak for the Java Buildpack, but I believe that most of this would apply to the other buildpacks as well.  The Java Buildpack releases every three weeks on average (the other buildpacks even more often) and every release contains CVE fixes for _some_ dependency.  So from that perspective, each release could be considered a security fix.  The key is that not every application uses every one of these dependencies and therefore might not be vulnerable and requiring a restage.

Given that lens (that it’s the dependencies that have vulnerabilities) there have been a couple of different attempts to expose dependency versions to users over the years.  The earliest one was the Java Buildpack’s `detect` output.  The API requirement is that it simply [write _something_ to `stdout`](https://devcenter.heroku.com/articles/buildpack-api#buildpack-api) for positive detection, but never specifies what.  The Java Buildpack kicks out a series of dependency versions (`open_jdk_jre=1.8.0_141 new_relic=3.35.1 memory_calculator=2.10.0`, etc.) from this script.  There are a couple of problems with this.  First the `detect` script isn’t always called (if you fix a buildpack by name or URI).  Second that the detect script can only be 255 characters (database column width) and our value is often 300-400 characters long so we have to truncate it, losing data.  And third, it only addresses the dependencies contributed by the buildpack; ideally this would also include any dependencies contributed by the application as well.

These days (I believe) the non-Java Buildpacks address the problem by writing a special file into the droplet that contains similar information.  It contains the dependencies contributed by the buildpack and if it doesn’t already, you could see it including application dependency information as well.  There is (was?) a [Pivotal project called AppDog](https://docs.pivotal.io/pcf-appdog/index.html) that would use this file (and I’m slightly hazy on the details here, so forgive me if they’re not quite right) to build up a repository of droplets and their dependencies cross referenced against CVEs.  This could be used for a dashboard, an alerting system, and possibly a CLI plugin to identify **applications with vulnerable dependencies**.

Setting aside that this was a Pivotal project (and whether it should have an open source equivalent), the basic idea is sound.  Vulnerabilities are much more fine grained than whether a given version of a buildpack was used to stage an application.  Vulnerabilities are against the artifacts within a droplet and used by the the application.  Any indication of vulnerability should be based on that information, not the version of the buildpack that was used to stage the application.  A tool that indicated vulnerability with mitigation strategies would also act as a superset of the required buildpack indication functionality, because the recommendation for outdated dependencies might be to update to a newer version of the buildpack.  I’d be much more amenable to working on solutions that moved in that direction, and I think we’d be much more successful in delivering usable value there as well.

Today of course, I think this isn’t a huge focus for us because so much of Cloud Foundry is oriented towards CI/CD pipelines and the promise that applications can be deployed multiple times a day.  I think that in a lot of companies this is true for new applications in development but it does often hide the fact that stable applications are not being regularly restaged and therefore are not having their dependencies refreshed.  There is a very real problem here that applications are becoming vulnerable over time, but I think we should be addressing this via dependency vulnerability surfacing rather than buildpack version surfacing.

**Comment by sclevine** [comment]
Definitely agree with Ben here about addressing this at a different level. It doesn't matter what buildpack version you're using if you're using older dependencies provided by the latest buildpack. Also, not all new buildpack versions fix security issues or provide new dependencies.

We generally release the non-Java buildpacks with a 1-3 week cadence. These buildpacks will warn you if you choose to use an EOLed dependency, or a older patch version of dependency. They will also warn you when the buildpack version changes.

From an engineering perspective, the feature you're requesting would not be straightforward to implement. @dkoper's suggestion (for system buildpacks only) is probably the best we could do without significant, coordinated effort. If you specify a buildpack URL, we have no way of knowing when a new buildpack is available at the URL (especially if you've used a `#` version specifier at the end of the URL). And even for the system buildpacks, CC has no concept of buildpack version.

To adequately complete this feature, the buildpack would need to communicate a version and version-check URL to CC for each app. Then CC would need to check the URL at some interval. The URL would need to provide data about new buildpack versions, and whether they contain security fixes.

**Comment by dkoper** [comment]
Thanks everybody for your input!

I am closing this issue, acknowledging that there is a valid use case, but from the input of the 3 PMs above clearly the CLI PM is not the domain expert who should be driving or coordinating this. Maybe the discussion can be resumed on the CF Dev distribution list where it can grab more people's attention, also helping us understand how wide support there is in pursuing the various alternatives mentioned.
