### ISSUE TITLE
Support buildpack version specification in application manifests

### ISSUE THREAD

**Issue by estadtherr** [cloudfoundry/cli#1197]
We have a deployment environment that has multiple Cloud Foundry installations (for operations vs. testing, different networks, etc.). Whether intentional or accidental, the set of available buildpacks and their versions and names can diverge among the different installations. This presents a challenge building reusable application manifests. For example, application A might require version 1.0 of buildpack X, whereas application B might require version 1.5 of buildpack X. These two buildpacks might be named 6 different things across the different installations. This makes it impossible to build a manifest file that works everywhere an application is deployed.

One solution would be to support semantic version qualifiers in the buildpack attribute in a manifest file, much the way NPM and other package managers support version requirements (e.g. https://docs.npmjs.com/misc/semver). An application manifest with this kind of a specification might look like:

```
---
applications:
- name: my-application
  stack: cflinuxfs2
  buildpack: python_buildpack>=1.5.20
  path: application-files
```

During deployment, the Cloud Foundry runtime would obey the version requirement when choosing a python_buildpack from the set of available buildpacks. If multiple Python buildpacks are available, the current ordering/sequencing logic would apply.

This would allow developers to express buildpack requirements in a way that would be portable across heterogeneous Cloud Foundry environments.

**Comment by dkoper** [comment]
This sounds like a feature request for the Cloud Controller, not the CLI.
@zrob, @nebhale, @sclevine Your thoughts?

**Comment by sclevine** [comment]
The platform has no concept of buildpack version. Adding a concept of buildpack version to the platform would require changes to the buildpacks, Cloud Controller, and CLI.

I'm not convinced that the platform should encourage the inclusion of old buildpacks, because old buildpacks very often supply dependencies that are vulnerable to known CVEs. We intentionally ship  the last two patch versions of all maintained version lines of language interpreters/compilers (ex. Node.js v4, v6, and v8) so that actively maintained apps can always be restaged.

If it's important to have complete certainty that apps always successfully restage, buildpacks can be uploaded with version numbers (or other identifies) in their names, and then removed when no apps are using them. (I think it would be awesome if the platform provided better support for this workflow.)

**Comment by nebhale** [comment]
I concur with @sclevine. At the moment, buildpack versioning is completely opaque to Cloud Foundry instances and in most cases, use a very generic name that hides version numbers.  Even though we go about it in different ways, all of the buildpacks attempt to present themselves as "evergreen".  Given this, I think the more promising avenue is how we can test the rollout of a new buildpack before it affects all applications.

**Comment by dkoper** [comment]
@estadtherr It seems your topic is a lot wider to work out in a CLI tracker issue.

I am wary of introducing into our client logic of going through all the available buildpacks and pick one based on a special buildpack name notation (which would also need to be implemented in other app manifest supporting clients).

You could try bringing it up on the CF Dev mailing list to get more people's view point on the issue?

Regards,
Dies Koper
CF CLI PM
