### ISSUE TITLE
Requesting a silent mode for cf push command

### ISSUE THREAD

**Issue by weymanf** [cloudfoundry/cli#1208]
## Command  

cf push mynodeapp

## What occurred

We are cf pushing an app as part of our deployment process. It runs inside of a bosh errand and it will fail because there is a limit to how much stdout it can read from an errand. The cf push using the nodejs buildpack emitted too many logs mostly containing the bundling of node modules.

Here is our bosh error.
```
Started running errand > push-apps/0. Failed: Response exceeded maximum allowed length (00:13:41)

Error 450001: Response exceeded maximum allowed length
```
I would list what the buildpack was logging out but I'm afraid it would be too long.

## What you expected to occur

I just want to request for a silent mode for cf push where it will omit the " Building dependencies" step.

## CLI Version  

cf-cli_6.23.1_linux_x86-64.tgz

## CC API Endpoint Version  

2.84.0

## Platform & Shell Details  

Should be ubuntu.

**Comment by dkoper** [comment]
Hi @weymanf 

I feel the issue lies with the limitation on output from the errand (https://github.com/cloudfoundry/bosh-lite/issues/239 ?), not with the cf CLI.
We would not want to add a flag to `cf push` for such a corner case - every additional flag on `push` makes it more difficult to learn, use and maintain.

Regards,
Dies Koper
CF CLI PM

**Comment by weymanf** [comment]
Okay thanks. Bosh has already fixed it on their side, but it's less frightening for people to upgrade a cli instead of an entire bosh director. 

I'm going to close this issue. As putting a flag on the cli for this edge case is a little funky.
