### ISSUE TITLE
Request for improvments for cups command responce 

### ISSUE THREAD

**Issue by alenakl** [cloudfoundry/cli#1243]
## on MAC
1) cf cups service-name -p "{"username": "XXXX","password": "****","host": "XXXX.cloudant.com","port": 443,"url": "https://XXXXXXXXX.cloudant.com"}"
2) cf bind-service app-name service-name 
3) cf restage app-name
4) cf env app-name

**According to command line responses:** 
1) service was created successfully
2) bind was successful. 

**In reality:**  this what you get with double quotes:
<img width="431" alt="screen shot 2017-10-10 at 2 53 59 pm" src="https://user-images.githubusercontent.com/15387867/31407574-fcdd3de0-adca-11e7-9e29-776af93bda10.png">

This what we have if we process the same command with single quote:
cf cups service-name -p '{"username": "XXXX","password": "****","host": "XXXX.cloudant.com","port": 443,"url": "https://XXXx@XXXX.cloudant.com"}'

<img width="462" alt="screen shot 2017-10-10 at 2 48 48 pm" src="https://user-images.githubusercontent.com/15387867/31407473-ac736cd0-adca-11e7-994c-97e475048647.png">
    

**What i expect:** if command wrapped in double quotes instead of single quotes as expected by CF  and command was not processed as expected - inform user by returning an error or warning message.

**Comment by dkoper** [comment]
We'll take a look.
The double/single quotes are expected by your terminal (hence being different depending on the platform you're on) - what the CLI gets passed in does not have the outside quotes anymore.
We can explore with what we do get passed in whether we can detect issues like this and act on them.

**Comment by XenoPhex** [comment]
Hi @alenakl we are closing this issue because what is being returned is not a CF CLI issue, it is a bash issue. When the command runs, it has no way of validation the user input as it receives these values as arbitrary strings from bash. To get around this we've added explicit documentation to the `cups` command stating that the user should use single quotes to force bash to treat that whole value as a single string.

Let us know if you have any feedback by reopening this issue or creating a new one. Thanks.
