### ISSUE TITLE
Is is possible to change the CF command name? 

### ISSUE THREAD

**Issue by jasonkoo** [cloudfoundry/cli#1250]
We want to change the cf command to some customized name. For example, instead of using the "cf apps", we want to use "mvsp apps".  Instead of using the "cf push", we want to use "mvsp push". 

I know we can use the alias command to create an alias for cf in Linux environment. But it is not a generic solution.

Is it possible to achieve that in the build and installation process? How to achieve that?
Thank you!

**Comment by dkoper** [comment]
Hi @jasonkoo 

There used to be a relative easy way to do that (as this `cf` was named `gcf` temporarily when it was originally developed to replace an existing ruby based `cf`) but since it was renamed `cf` 3 years ago we stopped supporting it.

We want to encourage CF users to use our "official" `cf` CLI to increase CF adoption by making it easy for them to work with any CF provider, so we prefer to not see forks and renames of our CLI with different commands and behaviours that would make it difficult for users of either to start working with other CF platforms.

Why do you want to customize the name?

Regards,
Dies Koper
CF CLI PM

**Comment by jasonkoo** [comment]
Hi @dkoper

Thanks for the quick reply.

The reason why we want to customize the name is the requirements from our customers. They want to rename the command to better align with their naming conventions.

**Comment by dkoper** [comment]
OK.
A different command name would also reduce portability of scripts using the cf CLI shared by the community for their users, and scripts they develop for `mvsp` to be shared with the CF community.
I hope you'll be able to talk them out of it.

**Comment by jasonkoo** [comment]
I will. Thank you for the clear explanation.
