### ISSUE TITLE
`cf add-network-policy` usage is inconsistent with other commands

### ISSUE THREAD

**Issue by dam5s** [cloudfoundry/cli#1279]
The CLI used to have the following policy: If an argument is required for a command it is not a flag.

The `cf add-network-policy` command is inconsistent with that.

From the help
```
USAGE:
   cf add-network-policy SOURCE_APP --destination-app DESTINATION_APP [(--protocol (tcp | udp) --port RANGE)]
```

`--destination-app` should not be required for passing the `DESTINATION_APP` as it is a required argument.

**Comment by dkoper** [comment]
Hi @dam5s 

Thanks for noticing.
This was intentional: we expected new network policy enhancements soon, so this way would allow us to add them easily, e.g. `cf add-network-policy SOURCE_APP (--destination-app APP_NAME | --new-feature VAL)`. If we had made APP_NAME a mandatory argument, it would have been clunky to extend this command to support e.g. service policies.

This policy of mandatory arguments and optional flags has been a constraint as we discover arguments in some cases should have been optional. So going forward, I'd like to loosen up that policy.

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Oops - didn't intend to close it already. Feel free to reopen if you want to continue the conversation!

**Comment by dam5s** [comment]
I see, that makes sense, thanks for the information!
