### ISSUE TITLE
cf push and cf delete+cf push yield different results

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#1280]
## Command  

```
# assume we are in the app directory, and the app has a cf manifest
cf push myapp
# remove an env var from the manifest
cf push myapp
```

## What occurred

after the second push the app still has the old environment variable

## What you expected to occur

after the second push the app does not have the old environment variable anymore; this is what would happen if we had run instead

```
cf push myapp
# remove an env var from the manifest
cf delete myapp 
cf push myapp
```

## CLI Version  

6.33.0

## CC API Endpoint Version  

2.74.0

## Any other relevant information  

Discussed in #cli on slack: https://cloudfoundry.slack.com/archives/C032824SM/p1512346522000073

**Comment by XenoPhex** [comment]
Hi @CAFxX thanks for creating this issue. Closing this issue because as mentioned in the aforementioned slack message, `cf push` has always been additive. Please also see this [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#precedence) for more information on precedence between manifests and command line options. Thanks again.
