### ISSUE TITLE
cf curl doesn't work on windows 7 in git bash

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry/cli#1301]
I am getting below error in Windows 7 in git bash:

```
$ cf curl /v2/info
{
   "description": "Unknown request",
   "error_code": "CF-NotFound",
   "code": 10000
}
```

The single quotes  or double quotes around the command does not work either.

However this : `cf curl v2/info`  works.

I am using `cf.exe version 6.33.1+c77e55743.2017-12-15` 

Thanks,
Chandan

**Comment by XenoPhex** [comment]
@ichandan16 the CF CLI does not support `git-bash`. This is because GoLang (which the CLI is written in) does not support it.

As for that issue, it works on command prompt and powershell on Windows (supported GoLang platforms).

**Comment by deadlysyn** [comment]
"You are running on an unsupported platform, please ensure all curl requests omit the leading slash." (or some UX-type message that avoids many enterprise users hitting this, getting confused, and calling support, to point them to KBs, all of which have leading /, which takes time to find this issue...and...  yes, even in edge cases UX is important.  This bit my customer today, and they would never have gotten past it alone, since they are not adept/allowed to search/use github.  :-(

Will try to push them to running all admin stuff from central jumpbox -- but many customers don't do that, and many people are confused by this in practice.  Are we sure we couldn't do anything to empathize and make it better even for the unloved-windows users?  :-)

**Comment by neillindberg** [comment]
Wow! Two years later and while I now have the solution - for git-bash and cf curl /v2/info op - I can't believe this issue is mentioned nowhere in docs on Cloud Foundry or IBM's implementation of CF. Holy moly, I sent this up the chain in support - and I'm a Linux guy working in a Windows regulatory space with not a lot of wiggle room. I tried quotes and all. Hmph. I can finally ssh into my cf instance with the info I needed from "/" v2/info. Thanks.
