### ISSUE TITLE
Should allow SSH connections to apps in starting state

### ISSUE THREAD

**Issue by keeganwitt** [cloudfoundry/cli#1356]
The CLI should allow Ssh connections to apps in starting state.  If you don't want to make this default behavior, at least give an argument that will allow connections to starting apps.  This is useful for example you are starting a Java app and it has a deadlock during startup.  Now allowing SSH makes it so I can't connect to JMX and see the problem.

## Command  

`cf ssh my-app`

## What occurred

Error opening SSH connection: Application "my-app" is not in the STARTED state

## What you expected to occur
SSH connection established.

## CLI Version  

6.35.2+88a03e995.2018-03-15

## CC API Endpoint Version  
2.82.0

**Comment by XenoPhex** [comment]
@keeganwitt is this also the case with `v3-ssh` or does it produce the same error?

**Comment by keeganwitt** [comment]
I'm not sure -- my client isn't on v3 API yet.

**Comment by XenoPhex** [comment]
Ok, we'll look into the implications of doing this. But we might be unable to allow this as the [API](https://apidocs.cloudfoundry.org/280/apps/retrieve_a_particular_app.html) only has two `state` values for the app, `started` and `stopped`. This means we only have so much knowledge as to the current state of the app. 

If the API is returning `stopped` for the given app, we're going to have to continue blocking it as the error recovery beyond that point gets super gnarly.

We'll also reach out to the diego team to figure out a potential alternative to this check.

**Comment by emalm** [comment]
Hey, @keeganwitt and @XenoPhex,

I sense there may be some confusion here about the desired state for a CF app versus the actual state of its instances. The CF CLI returns that "Application "my-app" is not in the STARTED state" error when the app developer has told the CF Cloud Controller API that the app is stopped. This error is reasonable: since the app is stopped, there should be no running instances into which to start an SSH session. So I don't think there's any behavior for the CF CLI to change in that case.

Separately, when an app is in the started state but its app instances are not yet running, the Diego subsystem does not allow a developer to start an SSH session, in part because the container may not even exist yet and in part because of certain internal implementation details of the CF SSH system itself. I've received feedback that it would be helpful to allow SSH access into those starting instances when possible, though, so we're interested in exploring ways to make that happen. In the meantime, as you've noted above, in cases where the app process itself starts and continues to run, you can select the `process` health-check type to circumvent the network-based active health checks and then use `cf ssh` to get access to the container environment. Again, I don't think there's anything for the CF CLI team to do to enable that work, as the connection attempts occur in the ssh-proxy component to which the CLI connects.

I've created https://www.pivotaltracker.com/story/show/156407268 in the Diego team Tracker project to keep track of this feature request.

Thanks,
Eric, CF Diego PM

**Comment by tjvman** [comment]
Closing this issue since there hasn't been any movement on the server side and the CLI can't support this use case until the server side does.

Please feel free to open a new issue once Diego support is available.
