### ISSUE TITLE
Fall back to .gitignore if no .cfignore exists

### ISSUE THREAD

**Issue by edshee** [cloudfoundry/cli#1363]
## Command  

`cf push`

## What occurred

If no `.cfignore` file is present then entire directory (minus the exceptions) are pushed to CF.

## What you expected to occur

If no `.cfignore` file is present then the cli falls back to use the `.gitignore` as a substitute meaning developers only need to maintain one ignore file.

## CLI Version  

All

## CC API Endpoint Version  

All

## Any other relevant information  

This practice is widely adopted in other platforms that have their own ignore file (Heroku, AWS etc...)

**Comment by XenoPhex** [comment]
Hey there @edshee,

Thanks for the request, however, we explicitly decided to have the `.cfignore` separable from the `.gitignore` and want to continue doing that going forward. While I understand the convenience, we always want the user to be explicit when doing a CF push, especially since there is no switch to ignore the `.cfignore` file. By falling back to the `.gitignore` file when the `.cfignore` file does not exist, the user might have issues pushing files that they don't necessarily want to commit. For these reasons, we're not going to fall back to using the `.gitignore`.

Let us know if you have further feedback, but we don't believe that a fall back is the right approach.
