### ISSUE TITLE
Plan schemas should be discoverable

### ISSUE THREAD

**Issue by deniseyu** [cloudfoundry/cli#1383]
## Proposed Extension  

`cf marketplace -s MY_SERVICE -p MY_PLAN`

## Why?

Arbitrary parameter schemas are part of the OSBAPI v2.13 specification, and many brokers and client tools are starting to rely on them to improve the app developer experience. In the current world, schemas are used for error validation, but not for setting expectations about what is possible. The only way to understand a service plan's supported parameters is to curl the service catalog, or otherwise consulting documentation. It would be great to have a unified experience.

As the CLI already performs this request during the `cf marketplace` command, it would be great to optionally expose plan details, including the schema, to app developers.

## What app devs could see

```
→ cf m -s kafka -p dedicated-vm
Getting service plan information for service redis-pm as admin...
OK

service plan: dedicated-vm
description: Kafka Dedicated Instance
free or paid: free
supported configuration parameters:
  create_service_binding:
    additionalProperties: false
    properties:
      topic:
        description: The name of the topic
        type: string
```

I don't have strong thoughts on the best way to display the schema to the user. I just went for YAML because it felt cleaner than JSON.

Thanks!

**Comment by deniseyu** [comment]
cc @Samze

**Comment by mattmcneeney** [comment]
Hey @deniseyu. We actually did some experimentation around how we could display this information in the CLI but never found an intuitive solution. What we did see is that developers tended to use trial and error when configuring services and bindings, and so by simply providing immediate feedback (validating parameters using schemas in the CLI code), the UX could be improved.

Other things we discussed were having interactive dialogs in the CLI but we didn't fully investigate what kind of experience this would provide and if the UX would be as expected.

**Comment by Samze** [comment]
Here is the original [feature narrative](https://docs.google.com/document/d/1uKJb2SaMgIhCM1bXEdT6NDAqCc3DhP_EdrM7Bwuh1xw/edit#) we wrote awhile back which contains a few UX designs. 

We actually wrote a `cf marketplace-v2` plugin that had the `-p` flag for user testing. And as @mattmcneeney stated, most users didn't use it and instead worked out the parameters with trial and error. Message me if you want to see the document that contains the results of the tests we did.

We had a few ideas:
1. Make schemas discoverable (as suggested).
1. Allow the user to generate a`parameters_template.json` file from the schema that they can fill in.
1. Provide an interactive experience where the user is prompted to enter values.

Schemas are powerful but are designed for machine consumption and not really for humans to parse and understand. I think rather than just exposing the schemas to users via the marketplace, we should wait for more feedback on the current experience from users/broker authors and then do a fresh round of UX research.

**Comment by Samze** [comment]
@abbyachau / @deniseyu I've sent you both invites to the doc.

**Comment by abbyachau** [comment]
Hey @deniseyu are you folks ok to close this issue until you've done more research on your side?

**Comment by deniseyu** [comment]
👍

**Comment by gberche-orange** [comment]
@FelisiaM any chance to reconsider this issue as part of v3 UX ? 

See related discussion in OSB API mailing list at https://groups.google.com/d/msgid/open-service-broker-api/c5ce005e-ecfe-45dd-8dac-6d01c7392f86n%40googlegroups.com?utm_medium=email&utm_source=footer
