### ISSUE TITLE
Unable to list all the apps in cf curl /v2/apps

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry/cli#1387]
## Command  

 `cf curl v2/apps` - returns first 50 entries.

## What occurred

```
$  cf curl v2/apps?results-per-page=200
{
   "description": "The query parameter is invalid: results_per_page must be <= 100",
   "error_code": "CF-BadQueryParameter",
   "code": 10005
}
```

## What you expected to occur

`cf curl /v2/apps` should return all the entries and `cf curl v2/apps?results-per-page=NUM` should return <= NUM entries

## CLI Version  

 $cf -v
cf.exe version 6.36.2+18ceab10f.2018-05-16

## CC API Endpoint Version  

api version:    2.94.0

## Platform & Shell Details  

RHEL Linux

**Comment by XenoPhex** [comment]
Hey @zrob can you explain the reasoning behind this.

**Comment by abbyachau** [comment]
Hey @ichandan16 we believe this is a CC API related issue/question. Could you please open an issue in the [Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng/issues) repo instead? We are closing this issue but please do not hesitate to reopen if you believe the issue lies with the CF CLI. Thanks.
