### ISSUE TITLE
cf api should provide the command to login with --sso if available

### ISSUE THREAD

**Issue by jedjebari** [cloudfoundry/cli#1400]
## Command
```
cf api
```
## What occurred

We are invited to login :
```
Not logged in. Use 'cf login' to log in.
```

## What you expected to occur
```
Not logged in. Use 'cf login' to log in with an internal user.
You can also use 'cf login --sso' to log in with your Federation system.
```
That would be the same behavior than the web-ui. The web-ui provides a link to login with SSO, when it is available.

## CLI Version

cf version 6.37.0+a40009753.2018-05-25

## CC API Endpoint Version
```
api version:    2.98.0
```

**Comment by abbyachau** [comment]
@jedjebari thanks for creating this. As mentioned we are currently refactoring the `login` command and we have a set of other priorities which means we will not be able to work on this in the near term. 

However, I'd like to scope the proposed message for when we are able to review this request. Since "Federation" is not intuitive for all our users, would the following update be sufficient for your users?

```
Not logged in. Use 'cf login' or 'cf login --sso'  to log in.
```

**Comment by jedjebari** [comment]
The text is ok for me. Thanks

**Comment by abbyachau** [comment]
Thanks @jedjebari we hope to be able to include this update in a future release. The work is scheduled, thanks again for your feedback.

**Comment by abbyachau** [comment]
Hi @jedjebari thanks for creating this request. We've implemented this enhancement and expect to include it in our next release. I'm closing this issue as done but please do not hesitate to reopen if you want to provide further feedback.
