### ISSUE TITLE
An app called "--help" cannot be deleted

### ISSUE THREAD

**Issue by deniseyu** [cloudfoundry/cli#1407]
During a Cloud Foundry new users training day run by @DanielJonesEB, @jpluscplusm encountered a scenario where someone accidentally pushed an app called "--help". Running `cf delete --help` is impossible. We are not trolling! 😂 😂 😂 

## CLI Version

The latest installable version as of June 23, 2018.

## CC API Endpoint Version

2.114.0

## Platform & Shell Details

Using hosted CF on Pivotal Web Services.

**Comment by deniseyu** [comment]
Perhaps the string `--help` should not be permitted as a name you can give to an app :trollface:

**Comment by jpluscplusm** [comment]
In this instance, the name of the app had a single `-` prefix: `-help`.

These cf-delete tactics failed:

```
$ cf delete -help
$ cf delete '-help'
$ cf delete "-help"
$ cf delete \-help
```

These CLI tricks failed:

- Renaming the app with `cf rename -help app-to-delete`
- `cf curl` to delete the app via its GUID: `cf app -help --guid` failed, so we had no GUID to call `cf curl` with.

This probably *would* have worked, but we only thought of it later: 

`CF_TRACE=true cf apps | grep -i guid`

... and then using the GUID in a `cf curl`.

We actually resolved the problem here by renaming the app via the WebUI, and then deleting it via the CLI.

**Comment by abbyachau** [comment]
Thanks @deniseyu we have a few other stories whereby users are using `-` or semicolons when they really should not be - this is relative low priority for us but at some point in the future will be adding forbidden characters. Thanks.

**Comment by heyjcollins** [comment]
Hello @deniseyu - this issue can't be reproduced on the current v6 or v7 lines (unable to push an app called `--help` or `-help` so I'm going to close this.
Please comment and reopen if I've missed something and this issue still applies to the v7 CLI.
