### ISSUE TITLE
warn users that unshare-private-domain might delete associated routes

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1417]
## Command

```
cf unshare-private-domain my-org gberche-private-domain.org
```

should warn admins about implicit route deletion that will be associated the running the command, or best require a --force option to complete when routes exist.

## What occurred

```
$ cf routes
Getting routes for org my-org / space gberche as gberche...

space     host            domain                       port   path   type   apps   service
gberche   gberche-route   gberche-private-domain.org

$ cf unshare-private-domain my-org gberche-private-domain.org
Unsharing domain gberche-private-domain.org from org my-org as gberche...
OK

$ cf routes
Getting routes for org my-org / space gberche as gberche...

space     host            domain                       port   path   type   apps   service
No routes found
```

## What you expected to occur

```
$ cf routes
Getting routes for org my-org / space gberche as gberche...

space     host            domain                       port   path   type   apps   service
gberche   gberche-route   gberche-private-domain.org

$ cf unshare-private-domain my-org gberche-private-domain.org
Warning: unsharing this private domain would also delete any existing route in the domain, 
Do you really want to continue ? [Y/N] N
Aborted

# -f flag supports automated non interactive usages, and skips the prompt
$ cf unshare-private-domain -f my-org gberche-private-domain.org
Unsharing domain gberche-private-domain.org from org my-org as gberche...
OK


$ cf routes
Getting routes for org my-org / space gberche as gberche...

space     host            domain                       port   path   type   apps   service
No routes found
```

## CLI Version

`cf version 6.37.0+a40009753.2018-05-25`

**Comment by abbyachau** [comment]
Thanks @gberche-orange for this - sounds sensible to add a warning.

**Comment by abbyachau** [comment]
@shalako @shubhaat

**Comment by shalako** [comment]
Hi @gberche-orange !

I'm confused by your example. I think maybe you tried to generalize the example and missed a spot.

```
$ cf unshare-private-domain my-org gberche-private-domain.org
Unsharing domain gberche-private-domain.org from org orange-private-sandboxes as gberche...
OK
```

I would think the CLI response for this would be
```
$ cf unshare-private-domain my-org gberche-private-domain.org
Unsharing domain gberche-private-domain.org from org my-org as gberche...
OK
```

Notice org `orange-private-sandboxes` should be `my-org`. Correct?

Otherwise the suggestion seems reasonable except the prompt would break tooling that automates this operation. Maybe a good candidate for v7, and include a `-f` flag to skip the prompt.

**Comment by gberche-orange** [comment]
thanks @shalako for spotting the typo and the -f option suggestion. Updated the proposal accordingly.

**Comment by abbyachau** [comment]
Hi @gberche-orange thank you for creating this issue. We plan on making CC API changes in V3 and the corresponding CLI change in V7 CLI. Please see this [story](https://www.pivotaltracker.com/story/show/162998046) here to track this work. Thanks all.

**Comment by abbyachau** [comment]
Hi @gberche-orange I'm closing this story since this has been implemented on the V7 CLI beta. We are close to announcing consumption of the V7 beta, and once we do, you'll be able to view this update. I'm closing this issue as done but please do not hesitate to get in touch or create a new issue if you have further feedback.
