### ISSUE TITLE
Feature Request: Allow for password prompting when using cf create-user

### ISSUE THREAD

**Issue by carefreepineapple** [cloudfoundry/cli#1421]
## Command
`cf create-user USERNAME PASSWORD`

## What occurred

Command requires the username and password be provided in-line and then both are recorded in the bash history.
If the password is omitted, a failure occurs.
`cf create-user user
Incorrect Usage: the required argument `PASSWORD` was not provided
FAILED`

## What you expected to occur

Command should prompt for password or at least have the option to prompt.
ie.`--prompt  
          Prompt for password`

## CLI Version

`cf version 6.36.1+e3799ad7e.2018-04-04`

## Why
This should help with security by preventing the password from being recorded.

**Comment by willmurphyscode** [comment]
Thanks for the suggestion! This is something I would like to see.

In the meantime, users can put a space before the command to keep it from being recorded in bash history. I know this isn't ideal, because you have to remember to do it, but it's what I recommend this for now. We might not be able to make the suggested change right away.

**Comment by abbyachau** [comment]
Hi @carefreepineapple we've implemented this feature on v7 cf cli beta. You can check it out [here](https://github.com/cloudfoundry/cli/releases/tag/v7.0.0-beta.25). Thanks for this feature request. I'm closing this issue as done but don't hesitate to get in touch if you have any feedback.
