### ISSUE TITLE
CF CLI returns confusing error response when creating an org

### ISSUE THREAD

**Issue by vitreuz** [cloudfoundry/cli#1441]
## Command

```
cf create-org
```

## What occurred
```
Creating org acceptance-test-org-N2X9Dz2utnmgW2ukLc9dew as admin...
OK
FAILED
Error accessing org <no value> for GUID': Server error, status code: 502, error code: 0, message: 
```

## What you expected to occur
A more meaningful error message. Also, the output of the error seems to be badly formatted.

For context, some requests during `cf create-org` command failed due to GCP 502s.

## CLI Version
```
cf version 6.36.1+e3799ad7e.2018-04-04
```
## CC API Endpoint Version
```
 "api_version": "2.120.0"
```

## CF Trace

N/A

## Platform & Shell Details

Linux

**Comment by abbyachau** [comment]
Hey @vitreuz thanks for reporting this. We have an existing story to change the exit code to `2` for when commands fail and returns a `502` error code so that folks can script retry logic more easily. Please track this work here https://www.pivotaltracker.com/story/show/159828965. We may not get to wrapping the error message but at least you'll have an exit code that you can act on more easily. I'm closing this issue, please track work in the aforementioned tracker story. Thanks again.
