### ISSUE TITLE
clone or copy routes from one app to another

### ISSUE THREAD

**Issue by pratapgowda007** [cloudfoundry/cli#1451]
User should be able to copy/clone routes from one app to another.

`cf copy-routes appname1 appname2`
(copy routes of appname2 and mapto appname1, if route is already mapped in appname1 then ignore)

Why do I need this functionality? 
While doing automated blue green deployment manually added routes were missing from new app.

[detailed usecase](https://stackoverflow.com/questions/52113478/cloud-foundry-copy-routes-from-one-app-to-another)

In general, user should be able to copy routes from one application to another. Is it possible to do?

**Comment by abbyachau** [comment]
Hi @pratapgowda007 are you able to use [variable substitution](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#variable-substitution) for this?

**Comment by pratapgowda007** [comment]
@abbyachau This is what I am currently doing defining host and domain from manifest. What I want is, facility to map all the routes from one app to another.
Eg:
I have an app "app1" with routes
```
host1.domain1.com
host2.domain2.com
```

while pushing app "app2" I need to copy all the routes from "app1" to "app2" 
cf push app2
cf copy-routes "app2" from "app1"  // someting like this

This will be very useful while doing blue green deployment.
Similarly user should able to delete all the routes for an app without knowing host and domain
`(cf delete-routes app2 --all)`

**What I am doing currently:**
Getting app information and parsing json to get routes
`cf app app1 | grep routes`
from the url's I am extracting host and domain and mapping
`cf map-route app2 ${domain} -n ${host}`

**Comment by abbyachau** [comment]
cc @shalako @shubhaat

**Comment by shalako** [comment]
@pratapgowda007 It seems to me your use case is this:

- appblue was deployed with a manifest
- someone mapped a route to blue but didn't add it to the manifest
- appgreen was deployed
- scripted cutover mapped only the routes from the manifest to appgreen, but not the manually added one

Is that correct?

First, knowing that your blue-green deploys are automated using a manifest, any routing changes should be made through your manifest ;)

However, this seems like it may be a good use case for our new zero-downtime deploy feature. Rather than deploying a second app, and remapping routes, you can can push a new version of the same app and CF will automate the routing cutover. For details, see https://docs.cloudfoundry.org/devguide/deploy-apps/zero-downtime.html for details.

cc @zrob

**Comment by abbyachau** [comment]
Hi @pratapgowda007 thanks for reaching out. We are closing this issue, please do not hesitate to reach out with feedback/further questions. Thanks.
