### ISSUE TITLE
proper argument check missing for enable/disable service access 

### ISSUE THREAD

**Issue by h0nIg** [cloudfoundry/cli#1530]
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Use optional organization parameter with disable-service-access and without argument (due to a bad script and an unset variable)

**What happened**
The CLI did not throw an error

```
$ cf disable-service-access blueprint -o ""
Disabling access to all plans of service blueprint for all orgs as admin...
OK
```

**Expected behavior**
The CLI should throw an error, because if the optional parameter is set, the argument must always be present. The behavior needs to be changed for enable-service-access and disable-service-access. If it is an intended behavior, the documentation needs to be changed:
```
cf help disable-service-access

USAGE:
   cf disable-service-access SERVICE [-p PLAN] [-o ORG]
```

and instead
```
cf help disable-service-access

USAGE:
   cf disable-service-access SERVICE [-p [PLAN]] [-o [ORG]]
```

**Provide more context**
- Ubuntu 16.04
- CLI version 6.41.0+dd4c76cdd.2018-11-28

**Comment by willmurphyscode** [comment]
Thanks for reporting this! It's important to us to have a good command line experience.

It looks to me like passing an empty string and omitting the argument are not quite the same. Consider the following:

```
$ echo $FOO
# a blank line is printed; $FOO is not set
$ curl -X "$FOO" google.com -v
# bad request because the verb is "".
```
It seems to me that we're doing the same thing - the CLI doesn't think you've omitted `-o`; it thinks you've intentionally set `-o` to be empty. While we appreciate the bug report, we probably won't prioritize this change at this time.

You may consider adding `set -u` to your scripts, so that unset variables are treated as errors.
