### ISSUE TITLE
`cf app <app-name>` fails to sometimes provide the last uploaded time.

### ISSUE THREAD

**Issue by crstamps2** [cloudfoundry/cli#1555]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
At some point between version `6.37.0+a40009753.2018-05-25` and at least `6.41.0+dd4c76cdd.2018-11-28` when running `cf app <app_name>` the `last uploaded:` line _sometimes_ doesn't populate. I haven't been able to make an app that reproduces this problem exactly but I do have traces of trying to run this same command for the same app, but different versions of the CLI.

**What happened**
When I run the following command I get no result:

```
➜ cf app example-app | grep 'last uploaded:'
last uploaded:
```

**Expected behavior**
I would expected to get something similar to what I have for other apps.
```
➜ cf app other-app | grep 'last uploaded:'
last uploaded:     Sun 31 Dec 19:00:00 EST 0000
```

**Provide more context**
- MacOSX High Sierra & Mojave, via iTerm
- CC API Version: 2.103.0

-----------------------------------------------------------
Attachments:

[cf_trace_v6_37.pdf](https://github.com/cloudfoundry/cli/files/2804266/cf_trace_v6_37.pdf)
[cf_trace_v6_42.pdf](https://github.com/cloudfoundry/cli/files/2804267/cf_trace_v6_42.pdf)

**Comment by abbyachau** [comment]
Hi @crstamps2 thanks for creating this issue. When you pushed your app, did you use the `no-start` flag by any chance? If so, here's a story that captures why the uploaded time does not appear in that case: https://www.pivotaltracker.com/story/show/162567227.

**Comment by willmurphyscode** [comment]
Between these two versions of the CLI, we switched from reporting app details from CC API v2's app endpoint to using CC API v3's app endpoint. In both cases the CLI more-or-less naively displays whatever application data is returned from CC API.

In newer versions of the CLI, we use the `created_at` field on the application's current droplet to determine the value in the last updated field. It looks like our attempt to retrieve that droplet in your 6.42 scenario was not able to retrieve the droplet for some reason:

```
REQUEST: [2019-01-28T10:47:48-05:00]
GET /v3/apps/08f11849-96ad-4ccf-a42f-25839ea664d4/droplets/current HTTP/1.1

...snip...

RESPONSE: [2019-01-28T10:47:49-05:00]
HTTP/1.1 404 Not Found
Content-Length: 128
Content-Type: application/json; charset=utf-8
Date: Mon, 28 Jan 2019 15:47:49 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Runtime: 0.009346
X-Vcap-Request-Id: 6cbec5e8-0128-4b6f-52be-3dd38e1fd76e::
3a995fd2-609f-42b3-83e0-6f9f31ab2514
X-Xss-Protection: 1; mode=block
{
 "errors": [
 {
 "code": 10010,
 "detail": "Droplet not found",
 "title": "CF-ResourceNotFound"
 }
 ]
}
```

@crstamps2 Do you think it's possible the app was being re-staged around the time your request was made? Can you give us a sense of how often this problem happens? (I'm trying to understand whether we're looking for a one-in-a-million race condition, or this happens most weeks, or what.)

@ssisil Is CC API aware of any issue where fetching the current droplet via the app GUID in v3 (request shown above) returns a 404? Is this operation ever expected to return a 404?

Thanks!

**Comment by crstamps2** [comment]
@willmurphyscode I do not believe it was being restaged. It happens fairly often. I actually have an example right now (but it's an app that I can't upload here :/) If you are willing, I would be happy to jump on a video chat and share my screen with you and show you. It's definitely more often than one in a million.

**Comment by willmurphyscode** [comment]
@crstamps2 We will be available in a [zoom meeting](issue1555call.cli.fun) for most of today if you want to join us.

**Comment by crstamps2** [comment]
@willmurphyscode I don't think your zoom link is right.

**Comment by ssisil** [comment]
@tcdowney - Can you answer this ? "Is CC API aware of any issue where fetching the current droplet via the app GUID in v3 (request shown above) returns a 404? Is this operation ever expected to return a 404?"

**Comment by crstamps2** [comment]
accidently hit the close and comment button...sorry for the extra tracker spam.

**Comment by willmurphyscode** [comment]
@crstamps2 no problem! Zoom link should be fixed.

**Comment by willmurphyscode** [comment]
We spoke to @tcdowney on the CC API team. It seems like `/v3/apps/some-guide/droplets/current` will return a 404 in several situations, namely if calls to `v2` endpoints have broken the association between the app and its current droplet. Right now, we have two examples of such calls: `cf push --no-start` and `cf push -s some-stack`. Both of these will put the app in a situation where the CLI cannot retrieve the last uploaded time because there is no current droplet until the app is re-staged.

It seems like @crstamps2 is not changing the stack or no start pushing, so we will work with the CC API team to learn what other actions can break the app's association with its current droplet.

**Comment by willmurphyscode** [comment]
I am closing this issue for now. Here's where things currently stand:

1. It is a known issue that apps in certain situations (see above) will have no `last uploaded` time when viewed through the CF CLI.
2. The semantics of what exactly `last uploaded` means can be confusing. If an app is rebuilt, but new bits are not pushed, should the `last uploaded` time change? The last uploaded field is sort of a interpretation of data stored in the Cloud Controller database, but it might because it's not obvious to the user what specific field in CC DB is being referred to.
3. Current feature work on how pushing apps is managed in CC API v3 will probably change what we mean by this field anyway.

Because of 2 and 3, it looks like we won't fix this right now. If anyone finds another situation in which `last uploaded` is blank, or a use case where this field's blankness is a big obstacle, feel free to re-open or open a new issue.
