### ISSUE TITLE
Provide official Docker image on DockerHub for running cf-cli

### ISSUE THREAD

**Issue by fedelopez** [cloudfoundry/cli#1578]
There is currently no official Docker image in the DockerHub containing a cf-cli app installed.

This would allow Cloud Foundry workloads to be deployed from within CI/CD platforms that are Docker friendly such as Gitlab or Bamboo - using a trusted Docker image.

I have talked to clients and some are reluctant to use non-official ones such as [this one](https://hub.docker.com/r/governmentpaas/cf-cli).

**Comment by RooSoft** [comment]
More than a year later... this missing feature would still be very appreciated!

**Comment by vchrisb** [comment]
@RooSoft this issue was only opened two month ago on 18th Feb *2019*...

**Comment by gcollombet** [comment]
Can we found documentation about the existing image usage ? The cf command is not accessible. My GitLab-CI Job return `/bin/bash: line 102: cf: command not found`

**Comment by abbyachau** [comment]
Hi @fedelopez and everyone, thanks for commenting on this. Although I can't provide an update today, please know we are tracking this request and hope to have an update soon. Please feel free to ping me on this issue if you don't hear back in a reasonable timeframe. Thanks again.

**Comment by tenjaa** [comment]
Hi @abbyachau 
Do you have an update? :)

**Comment by fedelopez** [comment]
Yes is there any update? we would really appreciate this 🙏

**Comment by candrews** [comment]
Can we please have an update on this issue?

This issue appears to be impacting many people and projects as evidenced by there being multiple docker images published for the `cf` cli, such as:
* https://hub.docker.com/r/governmentpaas/cf-cli
* https://hub.docker.com/r/ppiper/cf-cli
* https://hub.docker.com/r/emeraldsquad/cf-cli

But none of those are by Cloud Foundry and none are consistently maintained.

For the sake of security, maintainability, and usability, can Cloud Foundry please publish an official `cf` cli docker image, perhaps to it's `cloudfoundry` space on Docker Hub alongside the many other images already present there?

**Comment by a-b** [comment]
Thanks for your feedback. We will consider this feature. At this moment, our team is understaffed, and it could take a while.
I'm curious if you considered creating your image?

**Comment by candrews** [comment]
> I'm curious if you considered creating your image?

Of course, [as have many others including at least 3 G12 goverments: The US, UK, and Australia](https://github.com/cloudfoundry/cli/issues/1578#issuecomment-802127383). The problem is that it's effort for each image to be created, then it has to be maintained/updated each time a new `cf` release comes out. Inevitably, those images don't get maintained, and that leads to at best missing features and fixes from newer versions of `cf`, and at worse, security issues.

Others are also creating images. If your users use one of those images (because of the aforementioned effort problems with creating and maintaining their own), and then that image if compromised - that's not good for the user, and it looks bad for CloudFoundry.

:crossed_fingers: this issue can be resolved sooner rather than later, as it seems to me to be a problem just waiting to blow up.

**Comment by piyalibanerjee** [comment]
Hello! We are considering this feature as we understand the need and importance to the open source community and it has become highly requested. We have a couple questions for the community that will help us define requirements for an officially supported image: 
1. Are there any preferences for base images (or minimum base image)?
2. Is there any preference between having separate images with each CF CLI version (ie one image with v6, one image with v7, and one with v8) vs having one image with all versions of the CLI (v6, v7, and v8) bundled together and having `cf` point to the latest one?

**Comment by candrews** [comment]
> * Are there any preferences for base images (or minimum base image)?

alpine is generally preferred because it's small and well maintained.

> 
> * Is there any preference between having separate images with each CF CLI version (ie one image with v6, one image with v7, and one with v8) vs having one image with all versions of the CLI (v6, v7, and v8) bundled together and having `cf` point to the latest one?

Best practice for docker images is for them to be as small and as simple as possible to do the one thing they're supposed to do, echoing the so-called unix principle: do one thing, and do it well. Therefore, I think it's best to have separate images for each version.

**Comment by JenGoldstrich** [comment]
Hey @candrews here is a link to the team's dockerhub where we have published a v6 and v7 image https://hub.docker.com/r/cfcli/cf-cli/tags?page=1&ordering=last_updated, will update this with v8 when v8 is released, and update this for each version of the CLI we release. 

For pulling a specific syntax please use `docker pull cfcli/cf-cli:7.2.0`, for now I am closing this issue and leaving https://github.com/cloudfoundry/cli/issues/2174 open to track the v8 version of the docker image, please re-open or feel fre to comment on the other issue with any feedback or concerns.

Thanks!
Jenna
