### ISSUE TITLE
CF cups password prompt should hide user input

### ISSUE THREAD

**Issue by jpalmerpivotal** [cloudfoundry/cli#1583]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
We were creating a user provided service with `cf cups redis -p "host, port, password"` and we noticed that the password prompt is displayed in plaintext while entering it.

**What's the user value of this feature request?**
User security

**Who is the functionality for?**
People using `create-user-provided-service` and interactively entering password

**How often will this functionality be used by the user?**
Any time creating a user provided service

**Who else is affected by the change?**
N/A

**Is your feature request related to a problem? Please describe.**
No, just concerned

**Describe the solution you'd like**
Password input should be either asterisked out or blank

**Describe alternatives you've considered**
N/A

**Additional context**
example current workflow:
```
$ cf cups redis -p "host, port, password"

host> example-db.cloud.redislabs.com

port> 15462

password> hunter12
```

**Comment by AartiKriplani** [comment]
@jpalmerpivotal : Thank you for submitting the issue, we agree that it is not very ideal in terms of security to expose the password field. There is an option for passing the credentials in a file rather than plain text if you wish to hide the,.
We think that coming up with an exhaustive and predictable list of parameter names that should be treated as secure, would be really difficult in this case, just `password` won't cover all scenarios.
Please re-open the issue if you see any other issue with this command or option mentioned above.

Thanks,
Aarti & @ablease
