### ISSUE TITLE
"latest" stack association

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/cli#1592]
**What's the user value of this feature request?**
Ability to declare "latest" cf-stack association to an app, without having to explicitly declare the stack.

**Who is the functionality for?**
Everyone, but especially apps outside the control of CF admins-- especially useful for teams who deliver tiles, service brokers, etc.

**How often will this functionality be used by the user?**
Any time a stack migration is required.

**Who else is affected by the change?**
Very unlikely, but outside the scope of my understanding

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The ability to specify `stack: latest` in an application manifest, so that apps receive the latest available stack (assuming there is a logical ordering for stacks?) for their app, without having to explicitly declare a stack or upgrade it when new ones are available.

**Additional context**
I'm under the impression CF will no longer support cflinuxfs2. Apps need to be upgraded to cflinuxfs3. 

- Even if you don’t specify a stack in your app manifest, when new stacks are available, apps aren’t automatically updated to latest available. They stay at the stack they were created with using whatever the latest available stack was when it was first pushed. 
- So if you pushed your app when `cflinuxfs2` was latest, then `cflinuxfs3` comes along, your app stays at `cflinuxfs2` even if you cf-push or cf-restage.
- Restaging an app does not promote it to latest stack
- [The only way to promote an existing app’s stack with a cf-push is to specify the stack you want with `cf push -s cflinuxfs3`](https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html)

Many of our app teams use the cf-autopilot plugin which blue/green deploys in an entirely new app instance during push. It promotes to the latest stack because it's technically pushing a brand new app instance.

The real concern I have is with apps outside my control. What should I do if an app shipped with a third-party service is using an outdated stack? I guess I will need to login as admin and `cf push` their app with the latest stack.

Assuming there is a logical ordering to stacks (cflinuxfs2 --> cflinuxfs3 --> etc.), could an app's stack "float" to the latest?

**Comment by tjvman** [comment]
To the best of my knowledge, stacks do not have a logical ordering; introducing one would be difficult because operators can also [add custom stacks](https://docs.cloudfoundry.org/running/custom-stack.html), and CF also supports Windows stacks (such as https://github.com/cloudfoundry/windows2016fs). Unfortunately, this means that implementing this feature isn't currently viable, since we can't safely determine what is "latest". 

You may want to reach out to the maintainers of cflinuxfs2/3 (I believe it's @cloudfoundry/cf-buildpacks) and get their thoughts on the matter, as they'll likely have a clearer picture of what would need to change in order for this feature to be possible.
