### ISSUE TITLE
cf login host api showing error message

### ISSUE THREAD

**Issue by mdbaskaran123** [cloudfoundry/cli#1643]
I installed Pivotal cloud foundry.
In my command line if after i entered cf login,
API endpoint i am getting an error message, please find pasted image

![image](https://user-images.githubusercontent.com/50465575/57486810-85ea2c00-7274-11e9-806c-3500630c2424.png)

**Comment by abbyachau** [comment]
Hey there @mdbaskaran123 thanks for creating this issue. We'll need more information to be able to help. Could you provide trace logs or run the command in verbose mode. You should also try to curl the api directly to see if you can reach your instance. Thanks.

**Comment by mdbaskaran123** [comment]
![trace_file](https://user-images.githubusercontent.com/50465575/58209080-ef722d80-7cab-11e9-8727-b6942c2bc7c1.jpg)
Please find attached trace file

**Comment by mdbaskaran123** [comment]
![PCF_Question](https://user-images.githubusercontent.com/50465575/58209101-ff8a0d00-7cab-11e9-84e1-b1630964970b.jpg)
Please find attached api response from my browser

**Comment by mdbaskaran123** [comment]
![PCF_Error_Section3_Lecture9_4](https://user-images.githubusercontent.com/50465575/58209168-20526280-7cac-11e9-89e1-73f174ffad22.jpg)
Please find attached api response from my browser, ignore the previous one

**Comment by staylor14** [comment]
Hi @mdbaskaran123!

We've been unable to reproduce the problem that you're having under Windows 10 against the latest CLI.  We're wondering if you could download a [wget binary](https://eternallybored.org/misc/wget/) and run the following commands:

![windows-wget-success](https://user-images.githubusercontent.com/504044/60126001-de508c80-9741-11e9-9422-7c7c48e88d55.png)

From your error output, it looks like there's some kind of proxy involved that we don't understand.  We think maybe you're not triggering the same failure in your browser because your browser is properly configured.

You may want to try tools like `tracert` to see how your network traffic is trying to get out. From our machines, we ran a command like :
```
> tracert api.run.pivotal.io 

# Some output about how it hit a local gateway and then made it out to the ~wild~ interwebs
```

In any event, we do not believe that this is an issue with the CF CLI. These tips may show what network problems you have. Please feel free to reopen this issue if these networking troubles still seem to be CLI specific. 

Thank you kindly,
Steve and @bwasmith
