### ISSUE TITLE
`cf install-plugin cflocal` never finishes

### ISSUE THREAD

**Issue by paulvi** [cloudfoundry/cli#1647]
Hello

`cf install-plugin cflocal` never finishes,  
and there is no any errors or warning why it can't or what it is doing.

P.S. Environment Windows 10, Gish Bash and cmd.

![image](https://user-images.githubusercontent.com/1614482/57498470-92bb5e00-730e-11e9-9e44-fbb6f32da63a.png)

the same with Windows `cmd`

![image](https://user-images.githubusercontent.com/1614482/57509692-7c75c800-7337-11e9-907d-f6dc26f343f5.png)

The same for cfdev https://github.com/cloudfoundry-incubator/cfdev/issues/99 

**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
The latest version have been just installed the same day
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

**What happened**
A clear and concise description of what happen.

Unknown reason for `install-plugin` not proceeding.

**Expected behavior**

plugin installed with clear success message.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

1. `cf install-plugin cflocal`

It is unknown why exactly this happens, as not enough logging from `cf` util.

**Provide more context**
- platform and shell details : 
Windows 10
- version of the CLI you are running:
`cf version 6.44.1+c3b20bfbe.2019-05-08`

- version of the CC API Release you are on:
How to check?

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by abbyachau** [comment]
Hi @paulvi thanks for raising this issue. Have you tried reaching out to the plugin authors to see if they have any insights? Their information is here: https://plugins.cloudfoundry.org/. We'll try to help when we can. Thanks for your patience.

**Comment by staylor14** [comment]
Hi @paulvi,

We attempted to reproduce the issue locally on a Windows 10 Virtual Box image from Microsoft using `cmd`, and were unable to.  Also, our pipelines, which test the plugin commands, have remained green on Windows for quite a while.

Looking over the code in question, we don't really see where a "forever" hang could even happen.  The download should either fail with an error or time out.  Since we can't reproduce the problem, we're at a loss for how to help with your situation.

Our only guess would be to try the command on a different machine.

Please feel free to re-open this issue if you have ideas on how your environment may differ from ours so that we might be able to reproduce it.

Best regards,
Steve && @bwasmith
