### ISSUE TITLE
v3-push creates a route; v3-push --no-start does not

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1654]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

**What happened**

The following commands create an app with a mapped route even though manifest.yml does not specify a route:

```
cf v3-create-app myapp
cf v3-apply-manifest -f manifest.yml
cf v3-push myapp
```

After the droplet is created, the output shows a route being mapped:

```
   Uploaded droplet (28.4M)
   Uploading complete
   Cell 01662032-7b24-4fcc-8d2c-d79948d8dcff stopping instance 50a80fc2-4319-49a0-abf6-48e39a57fa78
   Cell 01662032-7b24-4fcc-8d2c-d79948d8dcff destroying container for instance 50a80fc2-4319-49a0-abf6-48e39a57fa78
   Cell 01662032-7b24-4fcc-8d2c-d79948d8dcff successfully destroyed container for instance 50a80fc2-4319-49a0-abf6-48e39a57fa78
OK

Setting app app-using-config-server to droplet e0632790-0f50-4f43-b214-08ca3dff35e1 in org cfdev-org / space cfdev-space as admin...
OK

Mapping routes...
OK
```

But if `cf v3-push --no-start` is used, then no route is mapped during `cf start` but was expected to do so:

```
cf v3-create-app myapp
cf v3-apply-manifest -f manifest.yml
cf v3-push myapp --no-start
cf start myapp
```

I tried `cf v3-start` but it fails:

```
$ cf v3-start myapp
This command is in EXPERIMENTAL stage and may change without notice

Starting app myapp in org cfdev-org / space cfdev-space as admin...
Assign a droplet before starting this app.
FAILED
```

So I guess I don't yet understand how the v3 commands work. How do I split out these commands?

**Comment by abbyachau** [comment]
Hi @drnic thanks for creating this. Please let us know what you trying to achieve, so that we can try to help. If you want to use `--no-start` using V3 commands, you can try:
`cf create-app  >> configure env vars >> cf p app` or `cf create-app` >> create-package >> cf stage >> cf set-droplet >> cf start`, for example.

**Comment by drnic** [comment]
Thanks @abbyachau

I referenced what I trying to achieve in the description and in the linked PR https://github.com/cloudfoundry/libbuildpack/pull/30. I apologise if I wasn't descriptive enough.

I have updated https://github.com/cloudfoundry/libbuildpack/pull/30 to setup env vars + logs prior to `cf v3-push`. This now avoids `cf v3-push --no-start` which doesn't generate routes.

Perhaps you can get rid of `cf v3-push --no-start` flag if its not supported/not implemented as expected; so as to encourage people to avoid it.

**Comment by abbyachau** [comment]
Thanks @drnic those commands are experimental, and we hope the experimental output text warns the user about the unpredictability of the command - that it does not work as the core `push` command and flags do. In order to direct our limited resources on working on the most valuable thing, we hope to put our efforts on supporting V7 where the commands backed by v3 will be default.
