### ISSUE TITLE
Issue with CF - drive is set fix

### ISSUE THREAD

**Issue by d022697** [cloudfoundry/cli#1661]
I have installed CF command line tool in past. For any reason it was referred to a specific drive "N" where folder  ".cf" for configuration was created. Now this drive is no longer available and when trying to start "cf" with any command I get the message: 
mkdir N:: The system cannot find the path specified.
FAILED

I re-installed CFI and checked registry files but nothing helps. I always get this message. Obviously CFI seems to store this path/drive locally but where and how can I solve this issue ?

Please help
Thansk and best regards
Harald

**Comment by abbyachau** [comment]
Hi @d022697 thanks, could you provide more details. What operating system are you on, what CLI version etc.

**Comment by d022697** [comment]
Hello,
in the meantime the issue has been solved but I don't really why it is working now. OP is Windows 10, CLI version is   6.44.1+c3b20bfbe.2019-05-08.  Anyway starting of cf.exe was looking for a drive that was nowhere defined - neither in environment variable nor in windows registry. In past I had a drive N, there .cf folder was created; then N was removed and so no longer accessible. I deleted/deinstalled cf.exe and installed it again and nevertheless whenever I started cf.exe by using cf <any command> I got the mentioned message saying no N drive and path available.

**Comment by abbyachau** [comment]
Hey @d022697 there's this [issue](https://lists.cloudfoundry.org/g/cf-dev/topic/31373001) here which might be related. Let me know if that helps, thanks.

**Comment by binoyskumar92** [comment]
Ok the solution for this issue atleast in my windows machine is as follows 
1. install cf tool in a drive which is accessible to you, say c:/cf_cli. 
2. Now run command ` setx CF_HOME c/cf_cli` to set CF_HOME as your installed directory. I'm using this syntax because I use git bash in windows as my terminal as I don't have access to cmd prompt.
3. Now copy the cf.exe file from the home folder to Users/<youruser>/bin folder
4. Exit git bash and run cf again it will work.
