### ISSUE TITLE
cf env shows weird output for non-string values

### ISSUE THREAD

**Issue by nictas** [cloudfoundry/cli#1704]
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I updated the environment of one of my applications directly through the CF controller's API - not through the CLI. I did a POST on `https://<URL>/v2/apps/<GUID>` with the following body:
```
{
	"environment_json": {
		"foo": true,
		"bar": 1234,
		"baz": ["a", "b", "c"],
		"qux": {
			"a": "b",
			"c": "d"
		},
		"quux": null
	}
}
```
Note that the values are *not* strings. I then ran `cf env` and saw the following:
```
User-Provided:
bar: 1234
baz: [a b c]
foo: true
quux: <nil>
qux: map[a:b c:d]
```
It looks like the values are simply converted to strings instead of being serialized to JSON as the CF controller does when setting them as actual environment variables in the container. This is what I see if I SSH into the application and run `env`:
```
quux=
foo=true
bar=1234
baz=["a","b","c"]
qux={"a":"b","c":"d"}
```

**What happened**
Described above.

**Expected behavior**
I expected to see the following output (maybe even with formatted JSON - just like VCAP_APPLICATION and VCAP_SERVICES):
```
User-Provided:
bar: 1234
baz: ["a","b","c"]
foo: true
quux: null
qux: {"a":"b","c":"d"}
```

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Update the environment of an application through the CF API and use lists, maps or `null`s as values.
2. Run `cf env`.
3. Look at the output.

**Provide more context**
- OS: Windows 10
- CLI version: 6.45.0+5f9ff16f9.2019-06-03
- CC API version: 2.136.0

**Comment by abbyachau** [comment]
Thanks @nictas for creating this issue, we'll take a look and get back to you when we can.

**Comment by acrmp** [comment]
Hi @nictas,

Thanks for reporting this issue. This is similar to #1534.

I think what's happening here is that the Cloud Controller will accept arbitrarily complex structures as environment variable values.

This doesn't really make sense - in the container the environment variable values are strings. It would make more sense for the Cloud Controller to either reject the request or to be liberal in what it accepts and serialise the environment variable value to JSON.

The alternative is for the CLI to treat the environment variable values as special and to serialise (flatten) parts of the JSON response from the Cloud Controller so that the serialised JSON representation is printed in the CLI output.

The CAPI team are out today for a holiday in the U.S. but we'll follow up with them when they return.

Thanks,

Andrew.

**Comment by abbyachau** [comment]
cc @ssisil @selzoc

**Comment by nictas** [comment]
Hi @acrmp,

_This doesn't really make sense - in the container the environment variable values are strings. It would make more sense for the Cloud Controller to either reject the request or to be liberal in what it accepts and serialise the environment variable value to JSON._ - Isn't the controller being liberal though? It accepts complex JSON structures and then serializes them to a string when setting them as an environment variable in the container. I expect that when I POST this:
```
{
	"environment_json": {
		"foo": true,
		"bar": 1234,
		"baz": ["a", "b", "c"],
		"qux": {
			"a": "b",
			"c": "d"
		},
		"quux": null
	}
}
```
I wouldn't get this when I GET the application afterwards:
```
{
	"environment_json": {
		"foo": true,
		"bar": 1234,
		"baz": "[\"a\", \"b\", \"c\"]",
		"qux": "{\"a\": \"b\", \"c\": \"d\"},
		"quux": null
	}
}
That would be a bit strange, IMO.

Rejecting complex structures is a possible "clean" solution from my point of view, but I doubt that the controller guys would go for it, because it would be a backwards incompatible change. I know of people from my organization that already take advantage of this "feature". Maybe in v3?

**Comment by selzoc** [comment]
CAPI definitely doesn't have any plans to change how we serialize environment variables into app containers.

**Comment by selzoc** [comment]
@nictas in the CAPI V3 API, we don't even allow complex structures!  See https://www.pivotaltracker.com/story/show/151335299 for details.

When trying your request in V3:

```
cf curl -X PATCH /v3/apps/<GUID>/environment_variables -d '{ "var": { "foo": true, "bar": 1234, "baz": ["a", "b", "c"], "qux": { "a": "b", "c": "d" }, "quux": null } }'
{
   "errors": [
      {
         "detail": "Non-string value in environment variable for key 'foo', value 'true', Non-string value in environment variable for key 'bar', value '1234', Non-string value in environment variable for key 'baz', value '[\"a\", \"b\", \"c\"]', Non-string value in environment variable for key 'qux', value '{:a=>\"b\", :c=>\"d\"}'",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

**Comment by acrmp** [comment]
Hi @nictas,

I think I'd recommend to avoid using complex structures as environment variable values.

If you need JSON within an environment variable value then marshalling the complex structure as JSON (so that the marshalled value is a string) is more explicit and in-line with how V3 will work.

Does that sound ok?

Thanks,

Andrew.

**Comment by nictas** [comment]
Considering that the V3 API does not support complex structures, yes, I'm fine with it. There's no reason for you to write code on your side that handles a quirk in the V2 API, which is deprecated AFAIK. :)
