### ISSUE TITLE
"cf push 'name'" doesn't check if a route already exists and adds apps to existing routes

### ISSUE THREAD

**Issue by svollath** [cloudfoundry/cli#1792]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
A new app was automatically added to an existing route.
cf input filtering test for special characters:
`cf push test/!1`
`cf push test/!/!1`
`cf push test/?2`
`cf push test/?/?2`

**What happened**
App name will be created as is, while the respective automatically created route will just remove the special characters to create the hostname.
When repeated with just changing special characters in the app name, this will lead to the same hostname, and a new app will get added to an existing route.
```
name      requested state   instances   memory   disk   urls
test!1    started           1/1         1G       1G     test1.10.162.231.83.omg.howdoi.website
test!!1   started           1/1         1G       1G     test1.10.162.231.83.omg.howdoi.website
test??2   started           1/1         1G       1G     test2.10.162.231.83.omg.howdoi.website
test?2    started           1/1         1G       1G     test2.10.162.231.83.omg.howdoi.website
```

**Expected behavior**
Either an error message stating that the second app would use an existing route, or automatically created routes to be unique (like in the sense, that you can't create apps with the same name), so e.g. if a route already exists, the hostname created would count up.

**To Reproduce**
`cf push test/!1`
`cf push test/!/!1`
`cf push test/?2`
`cf push test/?/?2`

**Provide more context**
- Linux bash
- cf version 6.34.0
- api version: 2.138.0

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by abbyachau** [comment]
Hey @svollath thanks we'll review as soon as we can and get back to you.

**Comment by ericpromislow** [comment]
Hello @svollath, 

Thank you for submitting this issue.

### Reproduction
We were able to reproduce the issue that you outlined. The steps we followed were:
```
$ cd APP1DIR

$ cf push 'test/!1'

$ cd APP2DIR

$ cf push 'test/!/!1'

$ cf routes                                                                              │
Getting routes for org org / space space as admin ... 

space   host     domain                  port   path   type   apps                            service
space   test1    example.com                                  test/!1,test/!/!1

$ curl test1.example.com
OUTPUT FOR APP1

$ curl test1.example.com
OUTPUT FOR APP2

$ curl test1.example.com
OUTPUT FOR APP1
... and so on, round-robin
```

### Assessment
We intentionally allow for multiple apps to be bound to the same route. This may cause confusion when special characters are stripped from app names to create default routes. 

We do not think an error is the correct way to handle this, but we think a warning when calling `cf push` would help.

Two possible warnings to issue:
1. Give a warning when a default route has [non-hostname characters](https://tools.ietf.org/html/rfc952) stripped from it
1. When we detect that the generated default route is bound to at least one other app

Also, a workaround is to specify an explicit route for each app that contains non-rfc-952-compliant characters.

Any feedback?

### Other interesting things to note:
We created a separate space and tried to do `cf push 'test/!/!/!1'` and that failed because the underlying route `test1.DOMAIN` was owned by the first space. Again, this is by design.

```
$ cf target -o space2

$ cf push test/!/!/!/!1
Pushing app test/!/!/!/!1 to org org / space space2 as admin...
Getting app info...
The app cannot be mapped to route test1.example.com because the route exists in a different space.
FAILED
```

Special character push:
For example, these two commands create two different apps, but bound to the same route:
```
$ cf push féve

$ cf push fève
```
The route `fve.DOMAIN` will be bound to the two apps `féve` and `fève` because the route generator simply drops the non-conforming characters.


Best,
Eric and @bwasmith

**Comment by abbyachau** [comment]
Hey @svollath thanks for creating this issue. Could you speak to why you are creating app names (and as a result host names) with special characters? Does a route like `test/!1.example.com` resolve, for instance? Thanks.

**Comment by abbyachau** [comment]
Hi @svollath on the v7 cf CLI, we plan on disallowing `push` to succeed at all if you `cf p !/!/why` and the host name contains special characters. See [here](https://www.pivotaltracker.com/story/show/168811666) for more information. Just a note that the app name may contain special characters but if you don't provide a host name, we will use the app name as the host name. Please let us know if you have any questions/feedback.

**Comment by heyjcollins** [comment]
In the v7 CLI, special characters in the app name are disallowed and generate the following error:
```
For application 'fève': Failed to create default route from app name: Host must be either "*" or contain only alphanumeric characters, "_", or "-"
``` 

Now that the v7 CLI is GA'd we're no longer actively developing the v6 line so I'm going to close out this issue.
