### ISSUE TITLE
Cannot push docker image, disk quota is there but gives error

### ISSUE THREAD

**Issue by rahuldeepattri** [cloudfoundry/cli#1808]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [yes] I reviewed open and closed github issues that may be related to my problem.
- [ yes] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [no ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
Creating an application from a docker image

**What happened**
A clear and concise description of what happen.
FAILED - The app is invalid: disk_quota too much disk requested (requested 8192 MB - must be less than 4096 MB)
**Expected behavior**
The disk_quota is there 
```
C:\CWD>cf space-quota plan
Getting space quota plan info as ...
OK

total memory limit      30G
instance memory limit   8G
```

**To Reproduce**

Command - cf push
Manifest - 
---
```
applications:
  - name: dlqa
    docker:
      image: deeppavlov/squad_en
    random-route: true
    memory: 6G
    disk_quota: 8G
```

**Provide more context**
Recently changed the disk quota for the quota, in ui it is showing 8G only.
- platform and shell details - CMD
- version of the CLI you are running - latest stable
- version of the CC API Release you are on -  2.141.0

**Comment by abbyachau** [comment]
Thanks @rahuldeepattri for creating this issue. We will review and get back to you soon.

**Comment by JenGoldstrich** [comment]
Hello @rahuldeepattri !

The space-quota you created refers to RAM, rather than disk space.  The Cloud Controller API config controls the maximum size of applications. (see: https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#requirements) You would need to modify the Cloud Controller's config to change this, the CLI does not control maximum disk size. (see: https://github.com/cloudfoundry/capi-release/blob/bec1f1bae12a43f556f95157ba8997a4f9841f7a/jobs/cloud_controller_ng/spec#L752-L754 and field cc.maximum_app_disk_in_mb).

Thanks!

@ericpromislow and @JenGoldstrich CLI Community Team
