### ISSUE TITLE
Unable to run cf cli on windows

### ISSUE THREAD

**Issue by AmauryVanEspen** [cloudfoundry/cli#1880]
Hello

trying to install CF CLI on windows through .exe for CLI7 or the version 6,
cf command is not available neither in command prompt (cmd) or windows powershell.
event as admin.

https://packages.cloudfoundry.org/edge?arch=windows64&source=github
https://packages.cloudfoundry.org/edge?arch=windows64&version=v7&source=github

Thank you

Amaury

**Comment by AmauryVanEspen** [comment]
I've found a way to use it,
copy the .exe to root (C:\Users\Username) then run prompt with cf7.exe or cf.exe then the command.
alternatively, use "cd" or the direct path to the .exe
finally, you can add cf.exe in a environment variable in windows

**Comment by prasmaran** [comment]
I used "cf7 --help" instead to get going

`C:\Users\XYZ>cf7 login
API endpoint: https://api.xxxxxxxx.com

Email: Username
Password:

Authenticating...
OK`


- Installer version: **cf7-cli-installer_7.7.8_winx64**
- While uncommon, it's possible that there was a naming variation in the specific installer you downloaded, or perhaps some configuration step resulted in the executable being named **cf7.exe instead of the usual cf.exe**
