### ISSUE TITLE
CF7 REGRESSION terabytes are not supported for memory quota

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/cli#2069]
**Describe the bug and the command you saw an issue with**
Set quota to 1 terabyte using `1T`.

**What happened**
CF CLI failed with `Incorrect Usage: Byte quantity must be an integer with a unit of measurement like M, MB, G, or GB`.

**Expected behavior**
The quota is set to 1 terabyte. This was possible in CF6.

**Exact Steps To Reproduce**
`cf update-quota -m 1T`

**Provide more context**
- `cf version 7.1.0+4c3168f9a.2020-09-09`

**Comment by heyjcollins** [comment]
Thanks for bringing this to our attention @mike1808. 
This regression was not intentional, however given our overall priorities and the fact that a quota equivalent to a terabyte can be set by passing in a large `G` value, I'm not inclined to prioritize fixing this and I'm going to respectfully close this issue.

However... If you can help me understand the use-case(s) that **require** `T` support, I could be convinced otherwise..
Please feel free to re-open and comment if you'd like to continue discussing.

**Comment by DanielJonesEB** [comment]
Y'all can't leave this on a cliff-hanger! I'm fascinated as to the use case for 1TiB apps. I know the JVM can be a little bloated, but...
