### ISSUE TITLE
cf v7 aborts when /v3/resource_matches returns 504

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/cli#2155]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

Using cf v7 to push an app with tons of files, the `/v3/resource_matches` returns 504, then the cf cmd aborts, but cf v6 continues to upload all files, instead of exit.  here is cf v6 behaviour: https://github.com/cloudfoundry/cli/issues/1042#issuecomment-272552018

**What happened**
cf v7 aborts when `/v3/resource_matches` returned 504 , as below:

```
REQUEST: [2021-03-17T16:23:13+08:00]
POST /v3/resource_matches HTTP/1.1
Host: api.xx.x.x.x
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf.exe/7.2.0+be4a5ce2b.2020-12-10 (go1.13.15; amd64 windows)
{
  "resources": [
    {
      "checksum": {
        "value": "3449c2d062440fae3992b0b145dc4eb932a687ef"
      },
      "mode": "600",
      "path": "0/com.apple.LaunchServices-231-v2.csstore",
      "size_in_bytes": 3645440
    },
    ......
  ]
}


RESPONSE: [2021-03-17T16:27:43+08:00]
HTTP/1.1 504 Gateway Timeout
Connection: Keep-Alive
Content-Type: text/html
Date: Wed, 17 Mar 2021 08:27:42 GMT
Server: nginx
X-Backside-Transport: FAIL FAIL
X-Global-Transaction-Id: e72d1ee36051bd0021fc42d7
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>


FAILED

```

**Expected behavior**

cf v7 should continue to upload all local files when `/v3/resource_matches` returns 504, just as cf v6.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

run `cf push` in a folder with tons of files.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm): Windows and Mac
- version of the CLI you are running : 7.2.0 and 7.1.0
- version of the CC API Release you are on: cloud_controller_v3 / 3.96.0

**Comment by ljluestc** [comment]
The issue is that while Cloud Foundry CLI v6 continues to upload all files when encountering a 504 response, Cloud Foundry CLI v7 aborts the process. You expect Cloud Foundry CLI v7 to behave like v6 and continue uploading files.

As of my last update in September 2021, I don't have access to information about the latest developments and fixes in the Cloud Foundry CLI. However, here's what you might want to consider:

1. **Check for Updates**: Make sure you are using the latest version of the Cloud Foundry CLI (v7) available at the time. There might have been updates that address this issue.

2. **Report the Issue**: If you are experiencing this issue and believe it's a bug, you should consider reporting it on the Cloud Foundry CLI's GitHub repository. Provide all the information you've shared here, including steps to reproduce, context, and the expected behavior.

   GitHub Repository: https://github.com/cloudfoundry/cli

3. **Check Changelogs and Issues**: Browse the GitHub repository's issues and changelogs to see if there have been any discussions or changes related to this particular behavior.

Since this issue involves specific behavior and interaction with the Cloud Foundry CLI v7, it's recommended to engage with the community directly through the GitHub repository for the most accurate and up-to-date information.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
