### ISSUE TITLE
Command to list app memory & disk usage (as was removed from cf apps)

### ISSUE THREAD

**Issue by Luthien-in-edhil** [cloudfoundry/cli#2171]
I just discovered that the information about instances, memory, and disk was removed from the `cf apps` command in CF CLI v7.

Unfortunately, this makes it a lot harder to create an overview of the memory & disk usage of our organisation's application stack, because I now need to `cf app` on every application separately to compile those data. 
This adds up to a rather tedious job for the nearly 100 apps we have running instead of the few seconds that it used to take. 

Therefore I was trying to figure out how to add the missing columns and was a bit puzzled to read in [Upgrading to CLI v7 doc](https://docs.cloudfoundry.org/cf-cli/v7.html) that this functionality was removed altogether; and I couldn't find any other way to achieve the same summary overview. 

In this particular case I use that as part of our carbon footprint reporting, but it would be useful for anyone who is interested in an overview of their application's memory / disk usage. 

I can imagine that those columns were removed to improve readability, but if it was available as a switch - for instance, `cf apps -m` (show memory column), `cf apps -d` (show disk column) it wouldn't get in the way, either :)

Thanks!
Lúthien

**Comment by JenGoldstrich** [comment]
Hello @Luthien-in-edhil, thanks for submitting this request!

This removal happened because of a switch to using the [/v3/apps](http://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html#the-app-object) endpoint as opposed to the [v2 apps summary](https://apidocs.cloudfoundry.org/16.13.0/apps/get_app_summary.html) endpoint.  There isn't an equivlant apps summary endpoint in v3, although this has been previously requested on a [cloud controller issue ](https://github.com/cloudfoundry/cloud_controller_ng/issues/1990)

This might be something worth considering though, @a-b @piyalibanerjee @sethboyles, either in the CLI or in the Cloud Controller as this isn't the first time we've had requests for this.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
