### ISSUE TITLE
Defect for CF CLI (cf push fails when manifest file contains valid route information)

### ISSUE THREAD

**Issue by ranadeep-sh** [cloudfoundry/cli#2201]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

I saw an earlier defect (https://github.com/cloudfoundry/cli/issues/1966) coming back on CF CLI version **7.2.0+be4a5ce2b.2020-12-10**. In other words, I am trying to CF push my application JAR with a manifest file where a specific route has been specified for concerned application.
I have confirmed that the syntax of my CF command and Manifest file are correct via CF CLI **6.53.0+8e2b70a4a.2020-10-01**, which I had installed after un-installing version **7.2.0+be4a5ce2b.2020-12-10**. 

_**And the everything worked and deployed with indicated version of 6.53.0**_.

**What happened**
Please see attachment of command screenshot.
#
**Expected behavior**
CF push should be successful with concerned app deployed.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf --version`
2. Confirm that the installed version is **7.2.0+be4a5ce2b.2020-12-10**
3. Ensure that `your-application-manifest.yml` contains `route: your-hostname.your-domain-name` under `routes` for your application.
4. Run `cf push your-application.jar -f your-application-manifest.yml`
5. See error, as in attached screenshot.

**Provide more context**
- platform and shell details : **Powershell (version 5.1.18362.1714)** on **Windows 10 Enterprise (OS version 1909)**
- version of the CLI you are running : **7.2.0+be4a5ce2b.2020-12-10**
- version of the CC API Release you are on : **3.85.0**

![Defect_SpecifiedRoute_in_manifest_not_accepted_by_CF_Push](https://user-images.githubusercontent.com/19390028/131388803-98c98bda-3235-4002-b740-7b25e7691944.jpg)

**Comment by ranadeep-sh** [comment]
![Defect_SpecifiedRoute_in_manifest_not_accepted_by_CF_Push](https://user-images.githubusercontent.com/19390028/131388698-06db5de7-2e55-47ee-aa87-1c5c76378dba.jpg)

**Comment by jmotex** [comment]
It looks like the app name must be the first parameter after "cf push", even if in manifest file.  Your first param is the JAR filename.  So it's reading that and error is due to invalid chars in that "app name".  So change your command to have the app name as the first argument and your problem is fixed.  Whether cf push should be changed to read the app name from the manifest only is a different question - it's not how it's currently designed.

cf push --help
USAGE:
   cf.exe push APP_NAME [-b BUILDPACK_NAME]
   [-c COMMAND] [-f MANIFEST_PATH | --no-manifest] [--no-start] [--no-wait] [-i NUM_INSTANCES]
   [-k DISK] [-m MEMORY] [-p PATH] [-s STACK] [-t HEALTH_TIMEOUT] [--task TASK]
   [-u (process | port | http)] [--no-route | --random-route]
   [--var KEY=VALUE] [--vars-file VARS_FILE_PATH]...

   cf.exe push APP_NAME --docker-image [REGISTRY_HOST:PORT/]IMAGE[:TAG] [--docker-username USERNAME]
   [-c COMMAND] [-f MANIFEST_PATH | --no-manifest] [--no-start] [--no-wait] [-i NUM_INSTANCES]
   [-k DISK] [-m MEMORY] [-p PATH] [-s STACK] [-t HEALTH_TIMEOUT] [--task TASK]
   [-u (process | port | http)] [--no-route | --random-route ]
   [--var KEY=VALUE] [--vars-file VARS_FILE_PATH]...

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
