### ISSUE TITLE
Path cannot be a single '/' - Breaking change from 6 up to 7 versions

### ISSUE THREAD

**Issue by ericserafim** [cloudfoundry/cli#2352]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I am reporting a bug that others will be able to reproduce.

**Given** `cf push -f manifest.yml`
**When** the `manifest.yml` file contains at least one application route ending with `/` (slash)
**Then** the `cf cli` shows the error message `For application '<app_name>': Path cannot be a single '/'.`

**Expected behavior**
The same command runs on version 6 without issues. The issue only appears up to version 7.

**Comment by alexquiti** [comment]
Hi,
I'm asking to myself why this issue doesn't have any answer, this is a real breaking change migrating to cf CLI V7, the fix as a user is simple, just removing the **/** (slash) at the end of the route, but it's still a breaking change.
The message is not clear either when it talks about a path instead of the application route.
Thanks

**Comment by gururajsh** [comment]
Thank you for your submission. With a major version change, breaking changes are expected. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
