### ISSUE TITLE
Runtime error while running cf login

### ISSUE THREAD

**Issue by csymeonides** [cloudfoundry/cli#336]
I ran this command:

cf login -u cicsoi@uk.ibm.com -p <REDACTED> -o cicsoi@uk.ibm.com -s dev;

using this version of the CLI: 6.6.2-0c953cf
and this error occurred:

runtime error: invalid memory address or nil pointer dereference

stack trace:
goroutine 1 [running]:
main.generateBacktrace(0xc21000a000, 0xa)
	/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:140 +0xa9
main.handlePanics()
	/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:124 +0xfb
runtime.panic(0x90e3e0, 0x11523c8)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x0, 0x0, 0xac9528, 0x0, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:229 +0x23c
github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x0, 0x0, 0xac9528, 0x0, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:247 +0x95
github.com/cloudfoundry/cli/cf/api/authentication.UAAAuthenticationR

**Comment by goehmen** [comment]
@csymeonides It looks like the error is happening because Golang can't interprest a password that starts with '-'.  I suppose we should handle that use case better.  

However, I think the resolution to your issue is this:

`cf login -u cicsoi@uk.ibm.com -o cicsoi@uk.ibm.com -s dev`

If you issue that login string, the CI will prompt you for password.

Here is an example:
```
○ → cf login -a https://api.a1.pivotal.io -u goehmen@pivotal.io -o goehmen-org -s development
API endpoint: https://api.a1.pivotal.io

Password>
```

Please reopen if this does not resolve your issue.  Thanks

**Comment by csymeonides** [comment]
Hi, thanks for your reply, however my password doesn't start with '-'. Also I need to be able to login wihout user interaction, in order to run an automated build. PS I can't see a "reopen" option for this issue.

**Comment by goehmen** [comment]
Yes, but even tbhough your pwd does not start with a '-', the CLI interprets the next character after a '-p' to be the pwd.  Since your string is: 'cf login -u cicsoi@uk.ibm.com -p -o cicsoi@uk.ibm.com -s dev', the CLI picks up the '-o' as your pwd.  

All that aside, If you are looking for an automated login, use `cf auth` which was created for just this purpose.

**Comment by csymeonides** [comment]
Thanks, I'll try that! Sorry about the confusion, my normal command would actually have included my password, but I deleted it when I posted this issue (for obvious reasons). I'm sure I replaced it with something like "<REDACTED>" but it didn't come through for some reason. Anyway thanks again for your help.
