### ISSUE TITLE
command delete-service-broker should accept 'yes' as the user input

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry/cli#389]
when we tried the 'yes', it shows that the command is revoked, but input 'y', the command executed without errors.
we shall both accept 'yes' and 'y' for user input.

The same issue happened on command 'delete-service'

might be a issue related to locale, I'm using zh.CN for LANG and input 'yes'

**Comment by jberkhahn** [comment]
It seems like this is because we attempt to translate the word for "yes" into whatever language the user is on: https://github.com/cloudfoundry/cli/blob/master/cf/terminal/ui.go#L119

Is this acceptable behavior? I'm not sure. @goehmen what do you think? maybe we could do y, yes, and translated(yes)?

**Comment by camelpunch** [comment]
Looks like this was fixed by https://github.com/cloudfoundry/cli/commit/9d4c3b9a4c13a0d5dca40f6e21cefdf8e3f34b31
