### ISSUE TITLE
Args Parsing in Cf plugins.

### ISSUE THREAD

**Issue by jessexu20** [cloudfoundry/cli#475]
It seems that I cannot use the go flag lib [flag](https://golang.org/pkg/flag/)  to the arguments parsing when I do a cf plugin command, although I can access all the args and os.Args, but the Parse() doesn't work...
The command I use:

        cf <plugin_command> -intflag 1;
        cf <plugin_command> --intflag 1;

Source code: 

       func (c *MultiCmd) Run(cliConnection plugin.CliConnection, args []string) {
             .....
             numPtr:=flag.Int("intflag","123","CF Space")
             flag.Parse()
             fmt.Println(*numPtr)
       }

Output: I always got the default 123, no matter what i put. 

So, is there anything that cf prohibit this? or did I do something wrong? Thanks in advance.

**Comment by jberkhahn** [comment]
The args that are passed into Run() are not the actual os.Args that you would use with a normal go binary. There are a few additional flags that we use for interaction between the RPC server and the plugin cli_connection harness. To try to access intflag in your example, I would try something like:

```
func (c *MultiCmd) Run(cliConnection plugin.CliConnection, args []string) {
  myFlagSet := flag.NewFlagSet("plugin_command", flag.ExitOnError)   
  numPtr := myFlagSet.Int("intflag", 123, "CF Space")
  err := myFlagSet.Parse(args[1:])

  fmt.Println(*numPtr)
}
```

Basically, ignore using the actual os.Args and use the args[] we pass in in its place.

If you need any additional help, please feel free to reopen this issue.

**Comment by sbielasi** [comment]
It appears that if I specify a command line flag that is not explicitly handled in the code via a FlagSet instruction, no error or usage message is produced.   The same code but in a non-plugin go executable does produce such a message.  I confirmed this by using the EchoDemo plugin downloaded from https://github.com/cloudfoundry/cli/blob/master/plugin_examples/echo.go.   This plugin demo handles a single '-uppercase' command line flag intended to signal that all remaining text on command line be uppercased.   This works fine if I specify the '-uppercase' flag on the cf plugin command line but fails to produce a usage message if some other flag is specified.   

Here is the code segment that sets up flag processing.

   echoFlagSet := flag.NewFlagSet("echo", flag.ExitOnError)
   uppercase := echoFlagSet.Bool("uppercase", false, "displayes all provided text in uppercase")

  
Here is what happens when I run this plugin with various scenarios.   Note that when I specify a command line flag other than '-uppercase', the plugin does not produce an error or usage message.

**Plugin no command line flag**
$ cf echo no uppercase flag argument so dont uppercase this
no uppercase flag argument so dont uppercase this 

**Plugin command line -uppercase flag specified**
$  cf echo -uppercase uppercase flag argument so uppercase this
UPPERCASE FLAG ARGUMENT SO UPPERCASE THIS 

**Plugin unsupported command line flag specified**
$ cf echo -unsupportedflag never return from Parse but does not display usage message
(exits but no error or usage message is produced)

If I take the code contained in the plugin Run function and place it directly in a main function in a   *echo.go* file, build it and run it, I do get an error message if an unsupported command line flag is specified.

**No command line flag**
$ ./echo no uppercase flag argument so dont uppercase this
no uppercase flag argument so dont uppercase this

**Command line -uppercase flag specified**
$ ./echo -uppercase uppercase flag argument so uppercase this
UPPERCASE FLAG ARGUMENT SO UPPERCASE THIS 

**Unsupported command line flag specified**
flag provided but not defined: -unsupportedflag
Usage of echo:
  -uppercase
    	displayes all provided text in uppercase

Am I doing something wrong in the plugin that results in no error or usage message being produced?
