### ISSUE TITLE
create-service-key fails for ups and p-rabbitmq

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cli#508]
The following sequence of commands:
```
cf cs p-rabbitmq standard rmq
cf csk rmq mikey
```
fails after the `csk` (whether `rmq` is bound or not) with:
```
Creating service key mikey for service instance rmq as admin...
FAILED
Server error, status code: 400, error code: 10004, message: The request is invalid
```

Also, if rabbitmq is a user-provided-service (instance):
```
cf csk rabbitmq brian
```
fails with:
```
Creating service key brian for service instance rabbitmq as admin...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

The only ones I can get to work are `redis` and `mysql` services.

This is on version `/usr/local/bin/cf version 6.11.3-cebadc9-2015-05-20T18:59:33+00:00`, running against PCF 1.5.RC1. (I can't get 6.12.0 to work at all, perhaps because of the known issue installing from brew.)

**Comment by xingzhou** [comment]
For the 400 Bad request response, the possible reason could be the service broker does not support creating a service binding without an application, which means the service broker does not support service keys.

For the 500 internal error case, is there any detail exception info? like enabling the CF_TRACE and see the output? or can you share with us the concrete reproducing steps so that we can help to debug the issue?

**Comment by shalako** [comment]
The service broker may not support service keys (requires an app). Also, try CLI 6.12.1.

**Comment by goehmen** [comment]
@Zteve Did the CLI upgrade resolve the issue?  If not, please reopen the issue and we will take another look.
