### ISSUE TITLE
CF version compatibilty with CLI version

### ISSUE THREAD

**Issue by dave-chen** [cloudfoundry/cli#519]
Hi,

I need to use the new features in CLI v.6.12.0.
Can someone tell me which CF version is compatible to CLI v.6.12.0?

Thanks,
Dave

**Comment by simonleung8** [comment]
If you are already using the v6.x.x CLI, then you shouldn't have problem upgrading to v6.12.0. However, some of the newer features in v6.12.0 will require a more recent CF release.

**Comment by goehmen** [comment]
@dave-chen If you are going to 6.12.x, the latest is 6.12.2

But to more specifically address your question, we strive to be backwards compatible so that a newer CLI will work with older cf-release versions.  However, that means that the CLI will include commands that implement features not present in older versions of cf-release.  The answer to your question is that it depends on what cf-release (runtime) features you want to be able to use.  

You can see features released in cf-release versions here:  https://github.com/cloudfoundry/cf-release/releases

Hope this info helps.  If you still have questions, please reopen the issue and we will take a look.
