### ISSUE TITLE
Feature Request: rolling restart

### ISSUE THREAD

**Issue by davehr** [cloudfoundry/cli#524]
Hi,
We want to implement a rolling restart of an application. An example use case is when a service which is used by the app has been modified and the security groups of the app need to be changed.

Its not going to be too tough to implement it ourselves via some sequential calls to 'cf restart-app-instance', however I'm guessing this must be a fairly common requirement. Are there plans to add it as part of the CLI? 

Thanks
Dave

**Comment by drnic** [comment]
Perhaps have a look in https://plugins.cfapps.io for some CF plugin options

**Comment by goehmen** [comment]
@davehr  Basically, you need to restart the app because of the service change and you're looking for a way to do this instance by instance so that you have no downtime, right?

As Dr.Nic suggested, this plugin for Blue/Green Deployments could work for your use case:  https://github.com/krujos/scaleover-plugin.  It is included on  https://plugins.cfapps.io

**Comment by NaveenRajaMarri** [comment]
If i have a app with 5 instance ,due to some issue/any  other reason  i have to do rolling restart .... instead of below method ( running one after the other for 5 times)
cf app-restart instance 0
cf app-restart instance 1
cf app-restart instance 2
cf app-restart instance 3
cf app-restart instance 4
 
 by using a command in single line how can i run a command for doing rolling restart?.
