### ISSUE TITLE
CLI does not support manifest.yml merge syntax

### ISSUE THREAD

**Issue by pmeskers** [cloudfoundry/cli#528]
When trying to `cf push` with a manifest file that utilizes YAML's [merge syntax](http://yaml.org/type/merge.html), the CF CLI does not correctly use parse the merged attributes. 

This is due to the CLI's underlying usage of `candiedyaml` for YAML-parsing, which does not support this part of the YAML spec. 

This means our manifest.yml's cannot fully rely on YAML syntax, and that we cannot share common properties and configurations between certain applications. 

[Here](https://gist.github.com/squeedee/1f309f8264c97cc672fe) is a quick demonstration in Go that showcases how `candiedyaml` interprets the merge syntax incorrectly (it treats it just as another key in the map).

**Comment by squeedee** [comment]
@goehmen I worked with Paul to confirm that the issue exists in candiedyml

**Comment by goehmen** [comment]
@squeedee Is the proposed action to fix candiedyaml or move away from candied yam?

**Comment by squeedee** [comment]
@goehmen as far as I know, candied Yaml was started to handle a Legal issue with the license on https://github.com/go-yaml/yaml. Since then, apparantly, the legal team has given it the all clear (perhaps they modified the license), and even Bosh uses the go-yaml implementation. 

To my mind, it's pointless to maintain a second library with identical directions. The implementations are a little different, but go-yaml is entirely useable, and much more mature. Happy to hear other opinions, perhaps we should ask around.

**Comment by camelpunch** [comment]
Looks like we dropped candiedyaml in favour of goyaml, fixing this issue.
