### ISSUE TITLE
cf uups overrides existing json

### ISSUE THREAD

**Issue by fsproru** [cloudfoundry/cli#557]
Hello,

We found a mismatch between the documentation for [user provided service](https://docs.cloudfoundry.org/devguide/services/user-provided.html#user-uups) and the cli behavior. The documentation says that attributes that you do not supply are not updated but the cli overrides the existing attributes with the json passed in into cli. Here is how to reproduce it:

```sh
cf cups test -p '{"old_attribute": true}'
cf bind-service my_app test
cf env my_app

"user-provided": [{
  "credentials": {
    "old_attribute": true
  },
  "label": "user-provided",
  "name": "test",
  "syslog_drain_url": "",
  "tags": []
}]

cf uups test -p '{"new_attribute": false}'
cf env my_app

"user-provided": [{
  "credentials": {
    "new_attribute": false
  },
  "label": "user-provided",
  "name": "test",
  "syslog_drain_url": "",
  "tags": []
}]
```

Both old_attribute and new_attribute should appear in the output according to the documentation. It might be either a bug in the cli or that the documentation is outdated. 

Thanks,
Alex

**Comment by camelpunch** [comment]
A quick read of the code suggests that we just submit the new attributes, and do not request the existing ones and merge before submitting.

@kimahoff / @goehmen do you think this is a documentation issue, or should `cf uups` be able to merge given attributes with the remote ones?

**Comment by camelpunch** [comment]
@dkoper any ideas?

**Comment by camelpunch** [comment]
Also, closing in favour of Tracker.

**Comment by ragaskar** [comment]
Seems more like slightly unclear docs than anything else; in the example, rather than setting a single attribute, the user is specifying an entirely new hash. I do not think the docs suggest that any values will be preserved when specifying a new hash -- rather, values are preserved only when an individual attribute is updated (but I agree there's room for confusion here). In the case where the user provides a new hash I would expect everything to be overridden. 

(also, hey @fsproru ! It's been awhile!).

**Comment by fsproru** [comment]
@ragaskar, thanks for clarification, and yes, it's been awhile. Would love to catch up, feel free to ping me if you are in LA, will do the same when I'm in SF :wink:

**Comment by dkoper** [comment]
Docs have been improved now.

**Comment by fsproru** [comment]
Sweet! Thanks @dkoper
