### ISSUE TITLE
MinCliVersion in PluginMetadata not working

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/cli#582]
Hi there,

I have a plugin that only works with cli v6.12.1 and newer, so I was trying to set the MinCliVersion like this:
```
func (c *NozzlerCmd) GetMetadata() plugin.PluginMetadata {
	return plugin.PluginMetadata{
		[...]
                MinCliVersion: plugin.VersionType{
			Major: 6,
			Minor: 12,
			Build: 1,
		},
                [...]
```

But with my local cli installed (v6.12.3), I get the following error:
`Minimum CLI version 6.12.1 is required to run this plugin command`

```
$cf -v
cf version 6.12.3-c0c9a03-2015-08-31T20:29:00+00:00 
```

As a side note, if I set the MinCliVersion to 6.12.0, it works as expected.

**Comment by camelpunch** [comment]
Hey Johannes! We're trying to consolidate issues into Tracker. Please see the Tracker story for updates.

**Comment by krishicks** [comment]
This is due to us baking the SHA into the Version string.

We set the version as the contents of the VERSION file in the root directory plus the git SHA of the build (see `bin/replace-sha`). The tests surrounding version check (`utils/version_check_test.go`) don't account for this.

When we compare, say, "6.12.3-c0c9a03" to "6.12.1", the former gets broken down into a Version with Revisions looking like this: []int{6,12,0}, as we split on the dots and strconv.Atoi() the result. strconv.Atoi("3-c0c9a03") returns 0.

**Comment by dkoper** [comment]
We have fixed this issue. If you could verify it resolves the issue for you, we will make it available in the next release. Thanks!
Use the "edge" build to test it. Find the links in the last paragraph of https://github.com/cloudfoundry/cli#downloads
