### ISSUE TITLE
Self-update?

### ISSUE THREAD

**Issue by matadon** [cloudfoundry/cli#657]
Having spent a decent amount of time with the rather excellent CLI for PWS recently, I have a suggestion-slash-feature-request.

As a Unixhead that moved to Mac some years ago, I run Macports on my laptop, and it has a neat little feature: Whenever you want to update to the latest version, you can run `sudo port selfupdate`, and Macports will update itself.

While I haven't had much time to dig into the code, it seems possible to add something like this into the `cf` command-line client. We could even go as far as occasionally pinging home, say every could of weeks, to see if updates are available, and let the end-user know with a helpful message.

This would make the process of staying up-to-date easier, especially when it comes to deploying new kit (like the recent Diego upgrade).

**Comment by dkoper** [comment]
I like this idea. I believe lattice cli has such a feature too, where the cli version is tied much closer to the cluster version.

**Comment by CAFxX** [comment]
@matadon https://github.com/tcnksm/cf-plugin-update-cli (in the meanwhile)

**Comment by dkoper** [comment]
Rather than building such functionaliy in, with our own UX for the user to learn, we have added support for the familiar package managers (Homebrew for Mac OS, apt-get for Debian/Ubuntu, yum for Fedora/RHEL/CentOS):
https://github.com/cloudfoundry/cli/blob/master/README.md#downloads

I believe a package manager is in the works for Windows, in the meanwhile the plugin Carlo linked to supports Windows.
