### ISSUE TITLE
service commands send v1 query params even when used for v2 stuff

### ISSUE THREAD

**Issue by jberkhahn** [cloudfoundry/cli#713]
Hey guys,

We are starting to actually remove v1 service stuff. The actual fields will be still be accepted/returned to/from the v2 endpoints, but @dieucao would like to get them removed sooner rather than later.

I know at the least, `purge-service-offering` sends `provider=(blank)` even when -p isn't thrown. 

Thanks!
@jberkhahn and @swetharepakula
CF CAPI Team

**Comment by krishicks** [comment]
What should we use as a reference to know what fields need to be removed?

**Comment by jberkhahn** [comment]
If you check out apidocs, all the v1 params have been marked as deprecated, such as [binding options for creating a service binding,](http://apidocs.cloudfoundry.org/226/service_bindings/create_a_service_binding.html) [gateway-data for creating a service-instance,](http://apidocs.cloudfoundry.org/226/service_instances/creating_a_service_instance.html) or [all the ones here.](http://apidocs.cloudfoundry.org/226/services/delete_a_particular_service.html)

The only one we're sure of atm is provider for purge-service-offering. Will try and investigate some more and see if we can identify exactly which commands.

**Comment by krishicks** [comment]
Perfect. Thanks!

**Comment by dkoper** [comment]
Will wait and see if @jberkhahn can provide us with a full list of commands so we can address them all in one go as part of this issue. Cheers.

**Comment by youreddy** [comment]
Hello, 

Here's an updated list of endpoints that have been removed:

[Creating a Service Plan](https://apidocs.cloudfoundry.org/226/service_plans/creating_a_service_plan_(deprecated).html)

[All of the Service Auth Token endpoints] (https://apidocs.cloudfoundry.org/226/serviceauthtokens_(deprecated)/list_all_service_auth_tokens_(deprecated).html)

[Updating a Service Plan]
(https://apidocs.cloudfoundry.org/226/service_plans/updating_a_service_plan_(deprecated).html)
We didn't remove this one but we changed it so that users can only update the public field in service plans.

[Creating a Service](https://apidocs.cloudfoundry.org/226/services/creating_a_service_(deprecated).html)

[Updating a Service](https://apidocs.cloudfoundry.org/226/services/updating_a_service_(deprecated).html)

We also removed provider, url, and version as parameters on Services. 

Thanks, 
@youreddy & @karafelix
CF CAPI Team

**Comment by krishicks** [comment]
Since finishing the chore:

* cf purge-service-offering with the -p flag is gated by <=2.46
* migrate-service-instances is gated by <=2.46
* service-plans is gated by <=2.46
* update-service-plans is gated by <=2.46
* create-service-plans is gated by <=2.46
* delete-service-plans is gated by <=2.46

For the rest of the deprecated endpoints and attributes we checked that we're no longer using them. The only one that changed was `PUT /v2/service_plans/:guid`, where we were sending more than 'public' previously.

**Comment by jberkhahn** [comment]
Looks good to me. Thanks for the update.
