### ISSUE TITLE
Question: restart application instance without downtime 

### ISSUE THREAD

**Issue by blinse** [cloudfoundry/cli#777]
I am not sure if this is the best place to ask this question. Feel free to redirect me to the appropriate place in case it is not. 

In case we want to restart an application instance without downtime (e.g. to read new environment variables), what would be the recommended way to do so:

1) Scale the application to more than one instance, then use cf restart-app-instance to restart one instance at a time?
2) Use cf copy-source to create a new instance of the application. Then map the route to this new instance and  unmap the route from the old instance
3) Do a blue green deployment (requires that we have archived the pushed app somewhere)

Is there a bullet-proof script available for this?

Thanks in advance for feedback.

**Comment by dkoper** [comment]
Hi @blinse 

This is a valid place to ask, but if you're after best practices, you may be able to get more and faster feedback if you post your question to the CF Dev mailing list:
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/

**Comment by dkoper** [comment]
* Option 1 works on DEA's but not on Diego
* Option 2 after doing copy source you'll need to start the app to get it to stage again and after it's up then map the route
* Option 3 works for a lot of people. There are various blue-green plugins people have created, not sure if they take advantage of `copy-source`

**Comment by dan-kirberger** [comment]
Hi @dkoper, 

Could you explain why option 1 only work on DEA? Did the restart-app-instance command use to be synchronous on DEA? Anything to watch out for specifically on Diego?

I'm working on a "rolling restart" CF plugin. Testing against diego (pcf/pcfdev). My general plan is to do something like:
1. Restart one instance
2. Monitor app health until all instances are healthy
3. Repeat

Seems to work in testing so far. Eventually it would get smarter by scaling up first, performing multiple restarts per loop, requiring fewer instances to be started at any time, etc. We'll see if it catches on.

**Comment by dkoper** [comment]
@ematpl Do you remember why option 1 only works on DEAs? (I can't remember, but I assume I asked you or Nick)
Also, anything to watch out for?

**Comment by ematpl** [comment]
The sequential `cf restart-app-instance` approach will work with a Diego-backed CF so long as you don't intend to change any of the application attributes such as environment variables, and simply want to restart the instances and have the replacements run with the same configuration. When CC runs an app on Diego, it submits that workload to Diego as a DesiredLRP specification, which includes the environment variables as part of the context for the containerized workload to run. That specification is then immutable (apart from instance count and route mappings) and is not replaced until CC changes the app-version GUID on the app. That app-version doesn't change when the environment variables are changed, though, so CC does not propagate that change to the Diego backend without an explicit `cf restart`.

On the DEAs, that specification is more dynamic, as it comes entirely from CC on each instance start. So in a DEA-backed CF you can manually propagate an environment variable change as above by changing the set of environment variables on the app in CC, then restarting each instance so that the replacement instance picks up the new environment variables. While this model does make it possible to sneak an environment-variable or other change through, it is much harder to audit at runtime, as the only source of truth for the specification of the running instances is in each DEA's instances.json record.

The Diego team has done some preliminary work on specifying an API for rolling updates of a DesiredLRP specification, to give CC the ability to propagate such changes to the container runtime in a controlled way, and we look forward to starting to implement it in the near future.

Thanks,
Eric

**Comment by dan-kirberger** [comment]
Thanks a lot guys! We are just interested in restarting apps to force refresh config/clear in app caches.

**Comment by preetampalwe** [comment]
@blinse - So finally how did you managed to get env vars reflected in the app without any downtime?
I came across the same problem as yours and looking for a right solution. Will be interesting to know how you solved your problem?
I have already started a thread on https://lists.cloudfoundry.org/g/cf-dev/topic/22417959
In my case (just like yours) 
1. cf restart-app-instance has not worked for env vars
2. cf copy-source require target app to exists - and I am not aware of any app clone feature
So still looking for the solution

Appreciate any help ... 
Many Thanks!

**Comment by preetampalwe** [comment]
Hi @dan-kirberger - I just checked your plugin at https://github.com/dan-kirberger/cf-rolling-restart and as you said you are using cf restart-app-instance but does not bother about new env vars getting reflected after the instance restart. Maybe that's sufficient for your requirement. 
Thanks!
