### ISSUE TITLE
cf service-keys makes undocumented and unsupported REST request

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cli#826]
While tracing the `cf service-keys` against PWS (`2.54.0`) command using CLI `6.17.0+5d0be0a-2016-04-15` I noticed that the request `GET /v2/service_instances/<SERVICE_INSTANCE_ID>/service_keys` was made.  This API isn't [documented](http://apidocs.cloudfoundry.org/235/) by the CAPI team and probably should not be used as a result.

### Command
`service-keys`

### CLI Version
`6.17.0+5d0be0a-2016-04-15`

### CC API Version
`2.54.0`

### CF Trace
```
GET /v2/spaces/<SPACE_ID>/service_instances?return_user_provided_service_instances=true&q=name%3A<SERVICE-INSTANCE-NAME>&inline-relations-depth=1
GET /v2/services/<SERVICE_ID>
GET /v2/service_instances/<SERVICE_INSTANCE_ID>/service_keys
```

**Comment by dkoper** [comment]
@SocalNick The CLI has always used this API for this command, since its introduction one year ago. It seems the CLI team may even have submitted the PR to CC with this API:
https://www.pivotaltracker.com/n/projects/1299870/stories/87057920
https://www.pivotaltracker.com/n/projects/966314/stories/91469560

Can you confirm it's OK for us to keep using, and if so, document it, if not, let us know what other API to call, from what targeted CC version to do so and by when we should move over?
Cheers, Dies

**Comment by nebhale** [comment]
For reference, the other half of this issue is https://github.com/cloudfoundry/cloud_controller_ng/issues/582.  I figure one will be worked and one closed.  For my two cents, there's an API that's more efficient for implementing `service-keys`, so I'd go with changing the CLI.  That's obviously the more invasive choice though, so I'm fine with either way.

**Comment by dkoper** [comment]
Closing as the API we use is documented now. @nebhale Can you mention here the API you're referring to that's more efficient? We can have a separate story (we may have enough for an epic by now) on making more optimized API calls.

**Comment by nebhale** [comment]
@dkoper I was referring to [this message](https://cloudfoundry.slack.com/archives/capi/p1461616418000246).  Looking it over now, it's not obvious that it's more efficient (it'd depend on which way the join is done against the database.  Guess it's fine to leave it like this.
