### ISSUE TITLE
Docs don't include --health-check-type

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cli#835]
The [docs for push](http://docs.cloudfoundry.org/cf-cli/getting-started.html#push) don't mention `--health-check-type` that was introduced here: https://github.com/cloudfoundry/cli/issues/694

**Comment by dkoper** [comment]
@benmoss Thanks for pointing this out. Since we now have an auto-generated command reference guide, I'd like to look at removing command syntax from docs.cloudfoundry.org (as they become stale so easily) and replace them with links to the command reference guide. I am currently discussing with the Docs PM how to go about this.

**Comment by dkoper** [comment]
This issue has been resolved by replacing the stale usage with a link to the generated cli reference guide.
http://docs.cloudfoundry.org/cf-cli/getting-started.html#push
