### ISSUE TITLE
cf set-env needs a -q (quiet) option to not echo secrets to logs

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/cli#906]
### Command

```
cf set-env myapp MYSECRET password
Setting env variable 'MYSECRET' to 'password' for app myapp in org MyOrg / space sandbox as p...@pobox.com...
OK
```
### CLI Version

cf version 6.20.0+25b1961-2016-06-29
### Desired behavior:

```
cf set-env -q myapp MYSECRET password
Setting env variable 'MYSECRET' to '(redacted)' for app myapp in org MyOrg / space sandbox as p...@pobox.com...
OK
```

**Comment by dkoper** [comment]
Wouldn't `cf set-env myapp MYSECRET password > /dev/null` work just as well?

**Comment by pburkholder** [comment]
Yes, that's what I'm doing.

But the point of the output is to help identify if things have worked as expected, so it'd be useful.

**Comment by uvzubovs** [comment]
Shouldn't secrets be stored in user provided service instances?

**Comment by dkoper** [comment]
In `v3-set-env` we are no longer displaying the value in the output. Once we refactor `set-env`, we'll remove it there too.

**Comment by coobr01** [comment]
Can we get a status update on this issue? We'd like to  not echo sensitive information in our CI logs.

**Comment by abbyachau** [comment]
Hi @coobr01 thanks for reaching out. We'll review to see if we can make this change without a rewrite of the command. We'll revert soon. Thanks.

**Comment by bwasmith** [comment]
Hey @coobr01 ,

Thanks for following up on this. @willmurphyscode and I were taking a look at this today. 

Some of the things we came up with are:

We decided not to implement `-q` because it would require customizing our flag parsing too much. Right now, we permit things like `cf set-env my-app foo --bar`, so having an optional flag would require putting `-q` or `--quiet` as a special case in our argument parsing. 

We talked with @abbyachau this afternoon about ways to move forward. Our recommended way of proceeding would be to not show the value at all. Something like:

```
$ cf set-env my-app key my-secret-value
Setting env variable key for app my-app in org org / space space as admin...
OK
```
That way, users can tell if the command has succeeded, but will not accidentally print out credentials.

Unfortunately, the team is prioritized to work on other features at the moment and will not get to it right away. If anyone is up for it, the change seems quite straightforward. We believe it would just be here:
https://github.com/cloudfoundry/cli/blob/e910fa8ce394da253d6f26e59cb18850c3830ede/cf/commands/application/set_env.go#L72 with associated tests.

**Comment by abbyachau** [comment]
Hi @pburkholder thanks for creating this issue, and to everyone who has commented. We've moved forward with changing the output so that it no longer prints the value, only the key. I'm closing this issue as done. The update will be in our next release. Thanks again.

**Comment by Gby56** [comment]
@abbyachau is this new behavior available ? I seems like it's still not published but I might be wrong

**Comment by faizan-syed** [comment]
Hi Team , 

When I do `cf env my-app`. I am able to see all the secret values and password in plain text that I set as an environment variable. Is there any way to hide those secret values ?
