### ISSUE TITLE
Facilitate the use of multiple api targets with the Cloud Foundry CLI.

### ISSUE THREAD

**Issue by mpivotal** [cloudfoundry/cli#909]
This feels like it should be part of the main cf CLI binary:
https://github.com/guidowb/cf-targets-plugin

**Comment by dkoper** [comment]
Why?

This is one of many useful looking plug-ins published on [our community plug-in site](https://plugins.cloudfoundry.org/).
It is a design goal for the cf CLI try to provide simple commands that people can expand on or orchestrate using scripts and plug-ins, and avoid feature-creep (any further). So it's great to see this plugin, and I'd love to hear if there is enough interest from users out there to warrant making it a core functionality.

**Comment by dkoper** [comment]
Closing. The plugin seems useful, yet having been published on the CF community plugin site for over a year I was the first to report it doesn't work on Windows.
I'd like to revisit this feature request when I hear from enough users who'd benefit from this functionality to be in core instead of by way of a plugin.
