### ISSUE TITLE
Allow cf uups to merge existing credentials

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cli#938]
`cf uups` only sends newly set credentials and clobbers existing credentials, as described in #557. IMO, this is a counter-intuitive behavior, and has caused some confusion on my team. I think adding the option to merge existing credentials would be useful here. I wrote a cli plugin to do this at https://github.com/jmcarp/cf-mups, but I think it would make sense to incorporate credential merging into this repo instead of using a plugin.

**Comment by XenoPhex** [comment]
Hi @jmcarp thanks for creating this issue. We've updated the `uups` help text to be explicit about credential overrides. However, we will not plan on making any further changes to enhance the behaviour of this command.

**Comment by XenoPhex** [comment]
@stipx I've heard this issue from several people and created an issue to look into it further: https://www.pivotaltracker.com/story/show/156767059

**Comment by Samze** [comment]
@stipx Just to clarify are you talking about viewing the credentials of a user provided service instance or a service instance backed by a service broker?

**Comment by stipx** [comment]
@Samze imagine you have a buildpack integration for some service. Because of wrong credentials it is not able to start up so I'm not able to show the environment variables via `cf env <appname>`. 

The integration is using a user defined service for the credentials.

When I just want to update the wrongly entered endpoint URL (typo or whatever) and want leave the password and username unchanged I have to look them up as well just to enter the endpoint again.

So just printing the credentials of a service would help because then I could just print the credentials and copy them over in my update call.

Hope that clarifies the use case.
