### ISSUE TITLE
CF V6 installer is not working after installation

### ISSUE THREAD

**Issue by nitindhotre** [cloudfoundry/cli#94]
Hi Team,

I am using Windows 7(64) operating system. It got installed.. but I can not see it in installed programs of operating system. It is creating CloudFoundry folder under Program Files(X86) and inside of this folder cf.exe file is there.. when i am trying to run it.. it just gives prompt for fraction of seconds and gets closed. 

Please help me.

**Comment by ksujanpaul** [comment]
Error read/writing config:  unexpected end of JSON input


this  is my error how can i solve it

**Comment by tjarratt** [comment]
Woah. Hey there @ksujanpaul. This is some serious thread necromancy. This issue we're commenting on is from several years ago and seems entirely unrelated to the very serious problem of the cli not being able to read its config file.

It seems to me that you should submit a new github issue for the behavior you're seeing.

Since I'm here and thinking about it though, you may want to try removing the file at `~/.cf/config.json` - please note that removing that file WILL log you out of the cli, and remove any notion the cli had about orgs / spaces and even the CF instance you were targeting. The cf cli effectively uses that as a local store for what you are doing with your CF environment. Perhaps it became corrupted as part of some earlier action?
